Repository kubevirt/kubevirtci, pull requests merged in 2018-12, with the labels that each got.

#53 Install OLM on all openshift clusters
  README.md
  k8s/scripts/logging.sh
  manifests/ovs.yaml
  os-3.11/scripts/provision.sh
Labels: size/S

#54 Add local fix to deal with python-docker issue
  README.md
  manifests/ovs.yaml
  os-3.10-multus/scripts/provision.sh
  os-3.11/scripts/provision.sh
Labels: size/M

#52 Added Openshift 3.11 and k8s 1.12.2 with multus providers.
  README.md
  k8s-multus/1.12.2/README.md
  k8s-multus/1.12.2/provision.sh
  k8s-multus/1.12.2/publish.sh
  k8s-multus/scripts/provision.sh
  manifests/flannel.yaml
  os-3.11-multus/provision.sh
  os-3.11-multus/publish.sh
  os-3.11-multus/scripts/logging.sh
  os-3.11-multus/scripts/node01.sh
  os-3.11-multus/scripts/nodes.sh
  os-3.11-multus/scripts/provision.sh
Labels: size/XL
