Repository kubevirt/kubevirtci, pull requests merged in 2018-10, with the labels that each got.

#47 Fix ssh problem and OpenShift builds
  README.md
  cli/cli
  gocli/cmd/provision.go
  os-3.10-multus/scripts/provision.sh
  os-3.10/scripts/provision.sh
Labels: size/M

#44 Added cni plugins deployment files to the manifest folder.
  README.md
  k8s-multus/scripts/logging.sh
  k8s-multus/scripts/node01.sh
  k8s-multus/scripts/provision.sh
  manifests/bridge-conf.yaml
  manifests/cni-plugins-ds.yaml
  manifests/flannel.yaml
  manifests/kubernetes-multus.yaml
  manifests/macvlan-conf.yaml
  manifests/openshift-multus.yaml
  manifests/openshift-ovs-vsctl.yaml
  manifests/ovs.yaml
  manifests/ptp-conf.yaml
  os-3.10-multus/scripts/logging.sh
  os-3.10-multus/scripts/node01.sh
  os-3.10-multus/scripts/provision.sh
Labels: size/XL

#48 Specify genie version
  README.md
  manifests/flannel.yaml
  manifests/genie.yaml
Labels: size/S
