Repository kubevirt/kubevirtci, pull requests merged in 2019-10, with the labels that each got.

#146 hack: add simple pre-flight check to cluster-up
  Makefile
  cluster-up/check.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#155 Move only the pf we need into the kind node namespace
  cluster-up/cluster/kind-k8s-sriov-1.14.2/config_sriov.sh
  cluster-up/cluster/kind-k8s-sriov-1.14.2/manifests/network_config_policy.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#159 Kind use "registry" as registry name from inside the cluster
  cluster-up/cluster/kind/common.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#161 Update OKD 4.1 version
  cluster-provision/README.md
  cluster-provision/okd/4.1/provision.sh
  cluster-provision/okd/4.1/run.sh
  cluster-up/cluster/okd-4.1/provider.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#157 Don't use host kubectl when provisioning sriov provider
  cluster-up/cluster/kind-k8s-sriov-1.14.2/config_sriov.sh
  cluster-up/cluster/kind/common.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#163 Deploy github.com/intel/network-resources-injector to the cluster.
  cluster-up/cluster/kind-k8s-sriov-1.14.2/config_sriov.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#167 Tamper the sriov-network-operator image with a fixed tag
  cluster-up/cluster/kind-k8s-sriov-1.14.2/config_sriov.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#166 Add instructions how to create new OKD release image
  cluster-provision/okd/README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#168 cluster: add support for different runtimes
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#169 check.sh: improve detection of nested virt
  cluster-up/check.sh
Labels: approved, dco-signoff: yes, lgtm, size/S
