Repository kubevirt/kubevirtci, pull requests merged in 2019-07, with the labels that each got.

#76 Increase pods per node to 110 on openshift
  cluster-provision/os-3.11-multus/scripts/provision.sh
  cluster-provision/os-3.11/scripts/provision.sh
  cluster-up/cluster/os-3.11.0-crio/provider.sh
  cluster-up/cluster/os-3.11.0-multus/provider.sh
  cluster-up/cluster/os-3.11.0/provider.sh
Labels: approved, lgtm, size/S

#115 Fix os-3.11.0 provider image path
  cluster-up/cluster/os-3.11.0/provider.sh
Labels: approved, lgtm, size/XS

#114 Bump CentOS os 1905_1
  cluster-provision/README.md
  cluster-provision/centos7/Dockerfile
  cluster-provision/centos7/build.sh
  cluster-provision/centos7/publish.sh
  cluster-provision/k8s-genie/1.11.1/README.md
  cluster-provision/k8s-genie/provision.sh
  cluster-provision/k8s-multus/1.13.3/README.md
  cluster-provision/k8s-multus/provision.sh
  cluster-provision/k8s/1.10.11/README.md
  cluster-provision/k8s/1.11.0/README.md
  cluster-provision/k8s/1.13.3/README.md
  cluster-provision/k8s/provision.sh
  cluster-provision/os-3.11-crio/provision.sh
  cluster-provision/os-3.11-multus/provision.sh
  cluster-provision/os-3.11/provision.sh
  cluster-up/cluster/k8s-1.11.0/provider.sh
  cluster-up/cluster/k8s-1.13.3/provider.sh
  cluster-up/cluster/k8s-genie-1.11.1/provider.sh
  cluster-up/cluster/k8s-multus-1.13.3/provider.sh
  cluster-up/cluster/os-3.11.0-crio/provider.sh
  cluster-up/cluster/os-3.11.0-multus/provider.sh
  cluster-up/cluster/os-3.11.0/provider.sh
Labels: approved, lgtm, size/M

#116 Use correct env var to get sec nics
  cluster-up/hack/common.sh
Labels: approved, lgtm, size/XS

#118 Use cluster wide unique mac for secondary nics
  cluster-provision/README.md
  cluster-provision/gocli/cmd/run.go
  cluster-provision/okd/4.1.0/provision.sh
  cluster-provision/okd/4.1.0/run.sh
  cluster-provision/okd/4.1.2/provision.sh
  cluster-provision/okd/4.1.2/run.sh
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: approved, lgtm, size/S

#119 Kind sriov cluster
  cluster-up/cluster/kind-k8s-1.14.2/README.md
  cluster-up/cluster/kind-k8s-1.14.2/provider.sh
  cluster-up/cluster/kind-k8s-sriov-1.14.2/README.md
  cluster-up/cluster/kind-k8s-sriov-1.14.2/config_sriov.sh
  cluster-up/cluster/kind-k8s-sriov-1.14.2/manifests/kube-flannel.yaml
  cluster-up/cluster/kind-k8s-sriov-1.14.2/manifests/multus.yaml
  cluster-up/cluster/kind-k8s-sriov-1.14.2/manifests/sriov-cni-daemonset.yaml
  cluster-up/cluster/kind-k8s-sriov-1.14.2/manifests/sriov-crd.yaml
  cluster-up/cluster/kind-k8s-sriov-1.14.2/manifests/sriovdp-daemonset.yaml
  cluster-up/cluster/kind-k8s-sriov-1.14.2/provider.sh
  cluster-up/cluster/kind-k8s-sriov-1.14.2/sriovdp_setup.sh
  cluster-up/cluster/kind/README.md
  cluster-up/cluster/kind/common.sh
  cluster-up/cluster/kind/manifests/kind.yaml
  cluster-up/cluster/kind/manifests/kube-flannel.yaml
  cluster-up/ssh.sh
Labels: approved, lgtm, size/XXL

#123 Do not set TechPreview feature gate
  cluster-provision/README.md
  cluster-provision/okd/4.1.0/run.sh
  cluster-provision/okd/4.1.2/run.sh
  cluster-provision/okd/scripts/provision.sh
  cluster-up/cluster/okd-4.1.0/provider.sh
  cluster-up/cluster/okd-4.1.2/provider.sh
Labels: approved, lgtm, size/M

#122 Fix sriov kind provider
  cluster-up/cluster/kind/common.sh
Labels: approved, lgtm, size/XS

#124 Fix sriov ci local path
  cluster-up/cluster/kind-k8s-sriov-1.14.2/config_sriov.sh
Labels: approved, lgtm, size/XS

#120 Wire up secondary nics
  cluster-provision/README.md
  cluster-provision/base/scripts/dnsmasq.sh
  cluster-provision/centos7/Dockerfile
  cluster-provision/gocli/cmd/run.go
  cluster-provision/k8s-genie/provision.sh
  cluster-provision/k8s-multus/provision.sh
  cluster-provision/k8s/provision.sh
  cluster-provision/okd/4.1.0/provision.sh
  cluster-provision/okd/4.1.0/run.sh
  cluster-provision/okd/4.1.2/provision.sh
  cluster-provision/okd/4.1.2/run.sh
  cluster-provision/os-3.11-crio/provision.sh
  cluster-provision/os-3.11-multus/provision.sh
  cluster-provision/os-3.11/provision.sh
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/k8s-1.11.0/provider.sh
  cluster-up/cluster/k8s-1.13.3/provider.sh
  cluster-up/cluster/k8s-genie-1.11.1/provider.sh
  cluster-up/cluster/k8s-multus-1.13.3/provider.sh
  cluster-up/cluster/os-3.11.0-crio/provider.sh
  cluster-up/cluster/os-3.11.0-multus/provider.sh
  cluster-up/cluster/os-3.11.0/provider.sh
Labels: approved, lgtm, size/M

#129 Create secondary nics tuntap before qemu starts
  cluster-provision/README.md
  cluster-provision/base/scripts/dnsmasq.sh
  cluster-provision/centos7/Dockerfile
  cluster-provision/k8s-genie/provision.sh
  cluster-provision/k8s-multus/provision.sh
  cluster-provision/k8s/provision.sh
  cluster-provision/manifests/kubernetes-ovs-cni.yaml
  cluster-provision/manifests/openshift-ovs-cni.yaml
  cluster-provision/os-3.11-crio/provision.sh
  cluster-provision/os-3.11-multus/provision.sh
  cluster-provision/os-3.11/provision.sh
  cluster-up/cluster/k8s-1.11.0/provider.sh
  cluster-up/cluster/k8s-1.13.3/provider.sh
  cluster-up/cluster/k8s-genie-1.11.1/provider.sh
  cluster-up/cluster/k8s-multus-1.13.3/provider.sh
  cluster-up/cluster/os-3.11.0-crio/provider.sh
  cluster-up/cluster/os-3.11.0-multus/provider.sh
  cluster-up/cluster/os-3.11.0/provider.sh
Labels: approved, lgtm, size/M

#121 Preserve $DOCKER_PREFIX if given
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: approved, lgtm, size/XS
