Repository kubevirt/kubevirtci, pull requests merged in 2019-06, with the labels that each got.

#84 Create the ovs br1 on worker nodes for ocp 3.11
  README.md
  os-3.11-multus/scripts/node01.sh
Labels: approved, lgtm, size/XS

#86 Bump cluster network operator to version 0.8.0
  manifests/cna/operator.yaml
Labels: approved, do-not-merge/hold, lgtm, size/XS

#83 OKD provider improvements
  README.md
  gocli/cmd/okd/run.go
  gocli/cmd/ports.go
  gocli/cmd/utils/ports.go
  okd/4.1.0-rc.0/publish.sh
  okd/4.1.0-rc.0/run.sh
  okd/4.1.0/provision.sh
  okd/4.1.0/publish.sh
  okd/4.1.0/run.sh
  okd/base/Dockerfile
  okd/hacks/release-4.1
  okd/scripts/provision.sh
  okd/scripts/run.sh
Labels: lgtm, size/L

#90 Add more insecure registries to okd provider
  cluster-provision/README.md
  cluster-provision/okd/4.1.0/run.sh
  cluster-provision/okd/scripts/provision.sh
  cluster-up/cluster/okd-4.1.0/provider.sh
Labels: approved, lgtm, size/S

#88 Move dynamic cluster-up configs into _ci-configs dir
  .gitignore
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/k8s-1.11.0/provider.sh
  cluster-up/cluster/k8s-1.13.3/provider.sh
  cluster-up/cluster/k8s-genie-1.11.1/provider.sh
  cluster-up/cluster/k8s-multus-1.13.3/provider.sh
  cluster-up/cluster/okd-4.1.0/provider.sh
  cluster-up/cluster/os-3.11.0/provider.sh
  cluster-up/hack/common.sh
  cluster-up/hack/config.sh
  cluster-up/kubeconfig.sh
Labels: approved, size/L

#91 Ensure os-3.11.0-multus provider is using the new sha256 hash
  cluster-up/cluster/os-3.11.0-multus/provider.sh
Labels: approved, lgtm, size/XS

#92 Make okd console port configurable so people can access UI
  cluster-up/cluster/okd-4.1.0/provider.sh
Labels: approved, lgtm, size/XS

#89 Update README.md
  README.md
Labels: approved, lgtm, size/S

#94 virtctl.sh fix
  cluster-up/kubectl.sh
  cluster-up/virtctl.sh
Labels: approved, lgtm, size/XS

#95 Remove kubevirt specifics from external provider.
  cluster-up/cluster/external/README.md
  cluster-up/cluster/external/provider.sh
Labels: approved, lgtm, size/S

#97 Don't break run params when $OS_NFS_DIR isn't defined
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: approved, lgtm, size/XS

#93 Allow remote execute of commands with ssh.sh
  cluster-up/ssh.sh
Labels: approved, lgtm, size/XS

#75 enable audit log for os-3.11
  cluster-provision/README.md
  cluster-provision/os-3.11/scripts/provision.sh
Labels: approved, lgtm, size/M

#98 utilize new OpenShift images
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/os-3.11.0-crio/provider.sh
  cluster-up/cluster/os-3.11.0-multus/provider.sh
  cluster-up/cluster/os-3.11.0/provider.sh
Labels: approved, lgtm, size/XS

#100 Remove deprecated providers
  cluster-provision/README.md
  cluster-provision/k8s-multus/1.10.4/README.md
  cluster-provision/k8s-multus/1.10.4/provision.sh
  cluster-provision/k8s-multus/1.10.4/publish.sh
  cluster-provision/k8s-multus/1.11.1/README.md
  cluster-provision/k8s-multus/1.11.1/provision.sh
  cluster-provision/k8s-multus/1.11.1/publish.sh
  cluster-provision/k8s-multus/1.12.2/README.md
  cluster-provision/k8s-multus/1.12.2/provision.sh
  cluster-provision/k8s-multus/1.12.2/publish.sh
  cluster-provision/k8s/1.10.3/README.md
  cluster-provision/k8s/1.10.3/provision.sh
  cluster-provision/k8s/1.10.3/publish.sh
  cluster-provision/k8s/1.10.4/README.md
  cluster-provision/k8s/1.10.4/provision.sh
  cluster-provision/k8s/1.10.4/publish.sh
  cluster-provision/k8s/1.9.3/README.md
  cluster-provision/k8s/1.9.3/provision.sh
  cluster-provision/k8s/1.9.3/publish.sh
  cluster-provision/os-3.10-crio/provision.sh
  cluster-provision/os-3.10-crio/publish.sh
  cluster-provision/os-3.10-multus/provision.sh
  cluster-provision/os-3.10-multus/publish.sh
  cluster-provision/os-3.10-multus/scripts/logging.sh
  cluster-provision/os-3.10-multus/scripts/node01.sh
  cluster-provision/os-3.10-multus/scripts/nodes.sh
  cluster-provision/os-3.10-multus/scripts/provision.sh
  cluster-provision/os-3.10/README.md
  cluster-provision/os-3.10/provision.sh
  cluster-provision/os-3.10/publish.sh
  cluster-provision/os-3.10/scripts/logging.sh
  cluster-provision/os-3.10/scripts/node01.sh
  cluster-provision/os-3.10/scripts/nodes.sh
  cluster-provision/os-3.10/scripts/provision.sh
  cluster-provision/os-3.9-crio/provision.sh
  cluster-provision/os-3.9-crio/publish.sh
  cluster-provision/os-3.9/provision.sh
  cluster-provision/os-3.9/publish.sh
  cluster-provision/os-3.9/run.sh
  cluster-provision/os-3.9/scripts/logging.sh
  cluster-provision/os-3.9/scripts/node01.sh
  cluster-provision/os-3.9/scripts/nodes.sh
  cluster-provision/os-3.9/scripts/provision.sh
Labels: approved, lgtm, size/XXL

#104 Upgrade gocli go_rules version to 0.18.6
  cluster-provision/gocli/WORKSPACE
Labels: approved, lgtm, size/XS

#105 Secondary nics
  cluster-provision/README.md
  cluster-provision/gocli/cmd/run.go
  cluster-provision/okd/4.1.0/provision.sh
  cluster-provision/okd/4.1.0/run.sh
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/hack/common.sh
Labels: approved, lgtm, size/S

#101 enable audit logs for os-3.11.0-multus
  cluster-provision/README.md
  cluster-provision/os-3.11-multus/scripts/provision.sh
  cluster-provision/os-3.11/scripts/provision.sh
  cluster-up/cluster/os-3.11.0-multus/provider.sh
Labels: approved, lgtm, size/M

#106 Update gocli hash to remove fmt.Println
  cluster-provision/README.md
  cluster-provision/okd/4.1.0/provision.sh
  cluster-provision/okd/4.1.0/run.sh
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: approved, lgtm, size/S

#108 Use Exec for non TTY ssh commands gocli
  cluster-provision/README.md
  cluster-provision/gocli/cmd/BUILD.bazel
  cluster-provision/gocli/cmd/ssh.go
  cluster-provision/gocli/docker/docker.go
  cluster-provision/okd/4.1.0/provision.sh
  cluster-provision/okd/4.1.0/run.sh
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: approved, lgtm, size/M

#110 Compose correctly the secondary-nics at multinode
  README.md
  cluster-provision/README.md
  cluster-provision/gocli/cmd/run.go
  cluster-provision/okd/4.1.0/provision.sh
  cluster-provision/okd/4.1.0/run.sh
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: approved, lgtm, size/M

#111 enable auditing for k8s images
  cluster-provision/README.md
  cluster-provision/k8s-genie/scripts/provision.sh
  cluster-provision/k8s-multus/scripts/provision.sh
  cluster-provision/k8s/scripts/provision.sh
  cluster-up/cluster/k8s-1.11.0/provider.sh
  cluster-up/cluster/k8s-1.13.3/provider.sh
  cluster-up/cluster/k8s-genie-1.11.1/provider.sh
  cluster-up/cluster/k8s-multus-1.13.3/provider.sh
Labels: approved, lgtm, size/L

#102 Update local volume provisioner version to latest.
  cluster-provision/README.md
  cluster-provision/manifests/local-volume.yaml
  cluster-up/cluster/k8s-1.11.0/provider.sh
  cluster-up/cluster/k8s-1.13.3/provider.sh
  cluster-up/cluster/k8s-genie-1.11.1/provider.sh
  cluster-up/cluster/k8s-multus-1.13.3/provider.sh
  cluster-up/cluster/os-3.11.0-crio/provider.sh
  cluster-up/cluster/os-3.11.0-multus/provider.sh
  cluster-up/cluster/os-3.11.0/provider.sh
Labels: approved, lgtm, size/M
