Repository kubevirt/kubevirtci, pull requests merged in 2019-08, with the labels that each got.

#127 Provider for k8s 1.15.1
  cluster-provision/k8s/1.15.1/provision.sh
  cluster-provision/k8s/1.15.1/publish.sh
  cluster-provision/k8s/scripts/nodes.sh
  cluster-provision/k8s/scripts/provision.sh
  cluster-up/cluster/k8s-1.15.1/README.md
  cluster-up/cluster/k8s-1.15.1/provider.sh
Labels: approved, lgtm, size/L

#131 Fix kubectl invokation to the one from the provider
  cluster-up/cluster/kind/common.sh
Labels: approved, lgtm, size/XS

#126 Create 4.1 provider
  README.md
  cluster-provision/README.md
  cluster-provision/gocli/BUILD
  cluster-provision/gocli/Makefile
  cluster-provision/gocli/WORKSPACE
  cluster-provision/gocli/cmd/okd/run.go
  cluster-provision/okd/4.1.0/publish.sh
  cluster-provision/okd/4.1.0/run.sh
  cluster-provision/okd/4.1.2/provision.sh
  cluster-provision/okd/4.1.2/publish.sh
  cluster-provision/okd/4.1.2/run.sh
  cluster-provision/okd/4.1/provision.sh
  cluster-provision/okd/4.1/publish.sh
  cluster-provision/okd/4.1/run.sh
  cluster-provision/okd/scripts/provision.sh
  cluster-provision/okd/scripts/run.sh
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/okd-4.1.0/README.md
  cluster-up/cluster/okd-4.1.0/provider.sh
  cluster-up/cluster/okd-4.1/README.md
  cluster-up/cluster/okd-4.1/provider.sh
Labels: approved, lgtm, size/L

#132 Fix ssh.sh to use KUBEVIRT_PROVIDER instead of $provider_prefix
  cluster-up/ssh.sh
Labels: approved, lgtm, size/XS

#135 Attempt to get worker machine set until successful.
  cluster-provision/README.md
  cluster-provision/okd/4.1/run.sh
  cluster-provision/okd/scripts/run.sh
  cluster-up/cluster/okd-4.1/provider.sh
Labels: approved, lgtm, size/XS

#136 Use KUBEVIRT_NUM_NODES to determine the number of workers for OKD 4.1
  cluster-up/cluster/okd-4.1/provider.sh
Labels: approved, lgtm, size/XS

#134 Use the sriov operator to setup sr-iov in the kind sriov provider
  cluster-up/cluster/kind-k8s-sriov-1.14.2/config_sriov.sh
  cluster-up/cluster/kind-k8s-sriov-1.14.2/manifests/network_config_policy.yaml
  cluster-up/cluster/kind-k8s-sriov-1.14.2/manifests/sriov-cni-daemonset.yaml
  cluster-up/cluster/kind-k8s-sriov-1.14.2/manifests/sriov-crd.yaml
  cluster-up/cluster/kind-k8s-sriov-1.14.2/manifests/sriovdp-daemonset.yaml
Labels: approved, lgtm, size/L

#137 Fix typo
  cluster-up/cluster/k8s-1.11.0/README.md
  cluster-up/cluster/k8s-1.13.3/README.md
  cluster-up/cluster/k8s-1.15.1/README.md
  cluster-up/cluster/k8s-genie-1.11.1/README.md
  cluster-up/cluster/k8s-multus-1.13.3/README.md
  cluster-up/cluster/kind-k8s-1.14.2/README.md
  cluster-up/cluster/kind-k8s-sriov-1.14.2/README.md
  cluster-up/cluster/kind/README.md
  cluster-up/cluster/okd-4.1/README.md
  cluster-up/cluster/os-3.11.0-crio/README.md
  cluster-up/cluster/os-3.11.0-multus/README.md
  cluster-up/cluster/os-3.11.0/README.md
Labels: approved, lgtm, size/S

#138 Export KUBEVIRTCI_CONFIG_PATH to fix sriov provider.
  cluster-up/cluster/kind/common.sh
Labels: approved, lgtm, size/XS

#140 Replace the sriov cni image used by the openshift operator with the upstream one.
  cluster-up/cluster/kind-k8s-sriov-1.14.2/config_sriov.sh
Labels: approved, lgtm, size/XS
