Repository kubevirt/kubevirtci, pull requests merged in 2019-09, with the labels that each got.

#133 Add validation that no unexpected node exists after cluster up
  cluster-up/up.sh
Labels: approved, lgtm, size/XS

#141 Provider for k8s 1.14.6
  cluster-provision/README.md
  cluster-provision/k8s/1.14.6/provision.sh
  cluster-provision/k8s/1.14.6/publish.sh
  cluster-provision/k8s/scripts/provision.sh
  cluster-up/cluster/k8s-1.14.6/README.md
  cluster-up/cluster/k8s-1.14.6/provider.sh
Labels: approved, lgtm, size/L

#144 Increase disk size of the master node
  cluster-provision/README.md
  cluster-provision/okd/4.1/provision.sh
  cluster-provision/okd/4.1/run.sh
  cluster-provision/okd/hacks/release-4.1
  cluster-up/cluster/okd-4.1/provider.sh
Labels: approved, lgtm, size/M

#151 Allow the kind-sriov provider to have two nodes
  cluster-up/cluster/kind-k8s-sriov-1.14.2/config_sriov.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#156 Provide a cluster-specific name for the local registry.
  cluster-up/cluster/kind/common.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#153 okd-4.1: avoid permission denied running as user
  cluster-up/cluster/okd-4.1/provider.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#158 Provide a cluster based registry name - fix
  cluster-up/cluster/kind/common.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#154 Add multinic to okd4 provider
  cluster-provision/README.md
  cluster-provision/gocli/cmd/okd/run.go
  cluster-provision/okd/4.1/provision.sh
  cluster-provision/okd/4.1/run.sh
  cluster-provision/okd/scripts/run.sh
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/okd-4.1/provider.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#152 Add gocli qemu option to attach serial to PTY
  README.md
  cluster-provision/README.md
  cluster-provision/gocli/cmd/run.go
  cluster-provision/okd/4.1/provision.sh
  cluster-provision/okd/4.1/run.sh
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: approved, dco-signoff: yes, lgtm, size/S
