Repository kubevirt/kubevirtci, pull requests merged in 2019-02, with the labels that each got.

#57 Retry downloading images multiple times
  README.md
  gocli/cmd/run.go
  gocli/docker/docker.go
Labels: size/M

#60 Create kubevirt-testing image
  images/README.md
  images/kubevirt-testing/Dockerfile
  images/kubevirt-testing/build.sh
  images/kubevirt-testing/publish.sh
Labels: approved, lgtm, size/M

#59 Update Multus providers
  README.md
  k8s-multus/1.13.3/README.md
  k8s-multus/1.13.3/provision.sh
  k8s-multus/1.13.3/publish.sh
  k8s-multus/scripts/node01.sh
  k8s-multus/scripts/provision.sh
  manifests/cni-plugins-ds.yaml
  manifests/kubernetes-multus.yaml
  manifests/kubernetes-ovs-cni.yaml
  manifests/multus.yaml
  manifests/openshift-multus.yaml
  manifests/openshift-ovs-cni.yaml
  manifests/openshift-ovs-vsctl.yaml
  manifests/ovs.yaml
  os-3.11-multus/scripts/node01.sh
  os-3.11-multus/scripts/provision.sh
Labels: approved, lgtm, size/XL
