Repository kubevirt/kubevirtci, pull requests merged in 2019-04, with the labels that each got.

#71 Make k8s clusters offline bootable
  README.md
  k8s-genie/scripts/provision.sh
  k8s-multus/scripts/node01.sh
  k8s-multus/scripts/provision.sh
  k8s/scripts/node01.sh
  k8s/scripts/provision.sh
Labels: approved, lgtm, size/M

#70 option added to set docker daemon proxy setting
  README.md
  gocli/cmd/run.go
Labels: approved, lgtm, ok-to-test, size/M

#72 Include e2fsprogs in the tests image to use mkfs
  images/README.md
  images/kubevirt-testing/Dockerfile
Labels: lgtm, size/XS

#73 Minor touchups to examples
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS
