Repository kubevirt/kubevirtci, pull requests merged in 2020-04, with the labels that each got.

#331 Revert "Label k8s non master nodes as workers (#327)"
  cluster-up/cluster/k8s-provider-common.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#332 Label k8s nodes as workers
  cluster-up/cluster/k8s-provider-common.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#333 Minor cosmetic fixups in K8S.md
  K8S.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#335 Correct the username for oscollabus
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#334 Rebuild k8s-1.17 with selinux enabled
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#336 Enable PodPreset on Kind IPv6 in order to enable migration
  cluster-up/cluster/kind-k8s-1.17.0-ipv6/provider.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#338 Delete kubevirtci base
  cluster-provision/README.md
  cluster-provision/base/Dockerfile
  cluster-provision/base/build.sh
  cluster-provision/base/publish.sh
  cluster-provision/centos7/Dockerfile
  cluster-provision/centos7/scripts/dnsmasq.sh
  cluster-provision/centos7/scripts/download_box.sh
  cluster-provision/centos7/scripts/vm.sh
  cluster-provision/centos7/vagrant.key
  cluster-provision/centos7/vagrant.pub
  cluster-provision/centos8/Dockerfile
  cluster-provision/centos8/scripts/dnsmasq.sh
  cluster-provision/centos8/scripts/download_box.sh
  cluster-provision/centos8/scripts/vm.sh
  cluster-provision/centos8/vagrant.key
  cluster-provision/centos8/vagrant.pub
  cluster-provision/common-scripts/images.sh
  cluster-provision/fedora/Dockerfile
  cluster-provision/fedora/scripts/dnsmasq.sh
  cluster-provision/fedora/scripts/download_box.sh
  cluster-provision/fedora/scripts/vm.sh
  cluster-provision/fedora/vagrant.key
  cluster-provision/fedora/vagrant.pub
  cluster-provision/k8s/1.14/base
  cluster-provision/k8s/1.15/base
  cluster-provision/k8s/1.16/base
  cluster-provision/k8s/1.17/base
  cluster-provision/k8s/1.17/provision.sh
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#339 Delete the k8s-multus-1.13.3 provider
  cluster-provision/README.md
  cluster-provision/k8s-multus/1.13.3/README.md
  cluster-provision/k8s-multus/1.13.3/provision.sh
  cluster-provision/k8s-multus/1.13.3/publish.sh
  cluster-provision/k8s-multus/provision.sh
  cluster-provision/k8s-multus/publish.sh
  cluster-provision/k8s-multus/scripts/logging.sh
  cluster-provision/k8s-multus/scripts/node01.sh
  cluster-provision/k8s-multus/scripts/nodes.sh
  cluster-provision/k8s-multus/scripts/provision.sh
  cluster-up/cluster/images.sh
  cluster-up/cluster/k8s-multus-1.13.3/README.md
  cluster-up/cluster/k8s-multus-1.13.3/provider.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#337 dnsmasq: Create secondary networks
  cluster-provision/centos7/scripts/dnsmasq.sh
  cluster-provision/common-scripts/images.sh
  cluster-provision/k8s/1.14/base
  cluster-provision/k8s/1.15/base
  cluster-provision/k8s/1.16/base
  cluster-provision/k8s/1.17/base
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#340 Add a container_file_t tmpfs to every k8s lane for tests
  cluster-provision/k8s/1.14/provision.sh
  cluster-provision/k8s/1.15/provision.sh
  cluster-provision/k8s/1.16/provision.sh
  cluster-provision/k8s/1.17/provision.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#342 Port different bridge for secondary-nics to centos8
  cluster-provision/centos8/scripts/dnsmasq.sh
  cluster-provision/k8s/1.17/base
  cluster-provision/k8s/1.17/provision.sh
  cluster-provision/k8s/check-cluster-up.sh
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#341 Go back to using a fixed 35G disk size for Centos 8
  cluster-provision/centos8/scripts/vm.sh
  cluster-provision/k8s/1.17/base
  cluster-provision/k8s/1.17/provision.sh
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#344 Enable hugepages again
  cluster-provision/k8s/1.14/node01.sh
  cluster-provision/k8s/1.14/nodes.sh
  cluster-provision/k8s/1.14/provision.sh
  cluster-provision/k8s/1.15/node01.sh
  cluster-provision/k8s/1.15/nodes.sh
  cluster-provision/k8s/1.15/provision.sh
  cluster-provision/k8s/1.16/node01.sh
  cluster-provision/k8s/1.16/nodes.sh
  cluster-provision/k8s/1.16/provision.sh
  cluster-provision/k8s/1.17/node01.sh
  cluster-provision/k8s/1.17/nodes.sh
  cluster-provision/k8s/1.17/provision.sh
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/M
