Repository kubevirt/kubevirtci, pull requests merged in 2020-11, with the labels that each got.

#469 SRIOV provider fine tunes: reduce wait time for sriov-operator readiness
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#472 SRIOV provider, csrcreator: switch to self-sign certificates
  cluster-up/.gitignore
  cluster-up/cluster/kind-k8s-sriov-1.17.0/certcreator/certlib/selfsign.go
  cluster-up/cluster/kind-k8s-sriov-1.17.0/certcreator/certsecret.go
  cluster-up/cluster/kind-k8s-sriov-1.17.0/certcreator/go.mod
  cluster-up/cluster/kind-k8s-sriov-1.17.0/certcreator/go.sum
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/csrcreator/certsecret.go
Labels: approved, dco-signoff: yes, lgtm, size/XL

#480 sriov, Fix non allocatable PF list
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#482 cnao, Add KUBVIRT_WITH_CNAO_SKIP_CONFIG env
  cluster-up/cluster/k8s-provider-common.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#485 sriov, Update retry function description
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#483 cnao, Update CNAO manifests to v0.42.3
  cluster-provision/manifests/cna/network-addons-config-example.cr.yaml
  cluster-provision/manifests/cna/network-addons-config.crd.yaml
  cluster-provision/manifests/cna/operator.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#478 KIND infra, SRIOV proivder, Run in-memory etcd
  cluster-up/cluster/kind-k8s-sriov-1.17.0/provider.sh
  cluster-up/cluster/kind/common.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#488 Revert "config-sriov.sh: reduce wait time for operator readiness (#469)"
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#487 cnao, Update CNAO manifest in k8s provider folders to v0.42.3
  cluster-provision/k8s/1.17/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.17/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.17/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.18/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.18/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.18/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.19/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.19/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.19/manifests/cnao/operator.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#489 sriov, Fix certsecret logic in case of etcd timeout
  cluster-up/cluster/kind-k8s-sriov-1.17.0/certcreator/certsecret.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#491 k8s providers, Fix provision sanity check flakes
  cluster-provision/k8s/check-cluster-up.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#481 sriov, Fix waiting for pod's condition "Ready" logic
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
Labels: approved, dco-signoff: yes, lgtm, size/S
