Repository kubevirt/kubevirtci, pull requests merged in 2020-02, with the labels that each got.

#241 add kind v0.7.0 with ipv6 support
  cluster-up/cluster/kind-k8s-1.17.0-ipv6/README.md
  cluster-up/cluster/kind-k8s-1.17.0-ipv6/provider.sh
  cluster-up/cluster/kind/common.sh
  cluster-up/cluster/kind/manifests/kind-ipv6.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#262 ipv6 provider: fix provider name
  cluster-up/cluster/kind-k8s-1.17.0-ipv6/README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#256 Deploy Calico cni with k8s-1.17
  cluster-provision/cli/cli
  cluster-provision/k8s/scripts/cnis-map.sh
  cluster-provision/k8s/scripts/node01.sh
  cluster-provision/k8s/scripts/provision.sh
  cluster-provision/manifests/calico.yaml
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XL

#267 Creating provision common scripts directory
  cluster-provision/centos7/build.sh
  cluster-provision/centos7/publish.sh
  cluster-provision/cli/cli
  cluster-provision/common-scripts/cnis-map.sh
  cluster-provision/common-scripts/images.sh
  cluster-provision/k8s-genie/provision.sh
  cluster-provision/k8s-multus/provision.sh
  cluster-provision/k8s/provision.sh
  cluster-provision/os-3.11-crio/provision.sh
  cluster-provision/os-3.11-multus/provision.sh
  cluster-provision/os-3.11/provision.sh
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#260 Initial contribution guide
  CONTRIBUTING.md
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#246 Create k8s provider with Fedora31 nodes.
  cluster-provision/base/Dockerfile
  cluster-provision/base/scripts/download_box.sh
  cluster-provision/cli/cli
  cluster-provision/common-scripts/images.sh
  cluster-provision/fedora/Dockerfile
  cluster-provision/fedora/build.sh
  cluster-provision/fedora/publish.sh
  cluster-provision/k8s-fedora/1.17.0/provision.sh
  cluster-provision/k8s-fedora/1.17.0/publish.sh
  cluster-provision/k8s-fedora/check-cluster-up.sh
  cluster-provision/k8s-fedora/provision.sh
  cluster-provision/k8s-fedora/publish.sh
  cluster-provision/k8s-fedora/scripts/ceph-csi.sh
  cluster-provision/k8s-fedora/scripts/cgroups.sh
  cluster-provision/k8s-fedora/scripts/logging.sh
  cluster-provision/k8s-fedora/scripts/node01.sh
  cluster-provision/k8s-fedora/scripts/nodes.sh
  cluster-provision/k8s-fedora/scripts/provision.sh
  cluster-up/cluster/images.sh
  cluster-up/cluster/k8s-fedora-1.17.0/README.md
  cluster-up/cluster/k8s-fedora-1.17.0/provider.sh
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XL

#269 Update k8s-1.17.0 provider to use calico
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#263 Add more details to the troubleshooting document.
  cluster-up/cluster/kind-k8s-sriov-1.14.2/TROUBLESHOOTING.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#268 Use calico net plugin for kind ipv6 provider
  cluster-up/cluster/kind/common.sh
  cluster-up/cluster/kind/manifests/kube-calico.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XL

#272 Enable local registry in containerd when using kind-ipv6
  cluster-up/cluster/kind/manifests/kind-ipv6.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#242 Configure br_netfilter to fix DNS
  cluster-up/cluster/kind/common.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#278 Add ocp-4.4 sha back
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#280 Don't mess with system's caching settings
  cluster-provision/okd/scripts/provision.sh
  cluster-up/cluster/ocp-4.3/provider.sh
  cluster-up/cluster/ocp-4.4/provider.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#282 Put back USE_TTY mechanism for k8s
  cluster-up/ssh.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#281 Configure calico additional settings to work with NetworkManager
  cluster-provision/cli/cli
  cluster-provision/common-scripts/config-cni.sh
  cluster-provision/k8s-fedora/scripts/provision.sh
  cluster-provision/k8s/scripts/provision.sh
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#286 Add Or Mergi as reviewer
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#285 calico: Allow ip forwarding at containers
  cluster-provision/cli/cli
  cluster-provision/common-scripts/cnis-map.sh
  cluster-provision/common-scripts/config-cni.sh
  cluster-provision/k8s-fedora/scripts/node01.sh
  cluster-provision/k8s-fedora/scripts/provision.sh
  cluster-provision/k8s/1.10.11/provision.sh
  cluster-provision/k8s/1.11.0/provision.sh
  cluster-provision/k8s/1.13.3/provision.sh
  cluster-provision/k8s/1.14.6/provision.sh
  cluster-provision/k8s/1.15.1/provision.sh
  cluster-provision/k8s/1.16.2/provision.sh
  cluster-provision/k8s/scripts/node01.sh
  cluster-provision/k8s/scripts/provision.sh
  cluster-provision/manifests/cni/calico/manifest.yaml
  cluster-provision/manifests/cni/calico/script.d/001-nm-filter-calico-ifaces.sh
  cluster-provision/manifests/cni/calico/script.d/002-allow-ip-forwarding.sh
  cluster-provision/manifests/cni/calico/script.d/003-change-cidr.sh
  cluster-provision/manifests/cni/flannel-ge-12.yaml
  cluster-provision/manifests/cni/flannel-ge-16.yaml
  cluster-provision/manifests/cni/flannel.yaml
  cluster-up/cluster/images.sh
  cluster-up/cluster/kind/manifests/kube-calico.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#288 Export pod cidr
  cluster-provision/common-scripts/config-cni.sh
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#291 Fix kind-1.14.2-sriov provider
  cluster-up/cluster/kind-k8s-sriov-1.14.2/provider.sh
  cluster-up/cluster/kind/manifests/kube-flannel.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#290 kind-k8s-1.17.0-ipv6: fix title
  cluster-up/cluster/kind-k8s-1.17.0-ipv6/README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#293 Revert CNI to kindnet, due to kind not fully support ipv6.
  cluster-up/cluster/kind/common.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#295 Increase k8s provider number of cpus to 6
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS
