Repository kubevirt/kubevirtci, pull requests merged in 2020-05, with the labels that each got.

#347 Add a kind k8s cluster for 1.17
  cluster-up/cluster/kind-k8s-1.17/README.md
  cluster-up/cluster/kind-k8s-1.17/provider.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#366 Fix k8s provision
  cluster-provision/centos8/scripts/dnsmasq.sh
  cluster-provision/k8s/1.17/node01.sh
  cluster-provision/k8s/1.17/nodes.sh
  cluster-provision/k8s/1.17/provision.sh
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#358 provision k8s-1.18: Copy files to 1.18 directory, set version
  cluster-provision/k8s/1.18/base
  cluster-provision/k8s/1.18/ceph-csi.sh
  cluster-provision/k8s/1.18/logging.sh
  cluster-provision/k8s/1.18/manifests/ceph/ceph-secret.yaml
  cluster-provision/k8s/1.18/manifests/ceph/ceph-snapshotclass.yaml
  cluster-provision/k8s/1.18/manifests/ceph/ceph-storageclass.yaml
  cluster-provision/k8s/1.18/manifests/ceph/csi-attacher-rbac.yaml
  cluster-provision/k8s/1.18/manifests/ceph/csi-nodeplugin-rbac.yaml
  cluster-provision/k8s/1.18/manifests/ceph/csi-provisioner-rbac.yaml
  cluster-provision/k8s/1.18/manifests/ceph/csi-rbdplugin-attacher.yaml
  cluster-provision/k8s/1.18/manifests/ceph/csi-rbdplugin-provisioner.yaml
  cluster-provision/k8s/1.18/manifests/ceph/csi-rbdplugin.yaml
  cluster-provision/k8s/1.18/manifests/cnao/namespace.yaml
  cluster-provision/k8s/1.18/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.18/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.18/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.18/manifests/cni.yaml
  cluster-provision/k8s/1.18/manifests/local-volume.yaml
  cluster-provision/k8s/1.18/manifests/logging.yaml
  cluster-provision/k8s/1.18/node01.sh
  cluster-provision/k8s/1.18/nodes.sh
  cluster-provision/k8s/1.18/provision.sh
  cluster-provision/k8s/1.18/version
  cluster-up/cluster/images.sh
  cluster-up/cluster/k8s-1.18/README.md
  cluster-up/cluster/k8s-1.18/dev-guide.md
  cluster-up/cluster/k8s-1.18/provider.sh
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#368 macvtap-cni: bump macvtap-cni to v0.2.0
  cluster-provision/k8s/1.17/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.18/manifests/cnao/operator.yaml
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#373 Fix docker version issues, bump k8s-1.17 micro and temporarily disable dontaudit on k8s-1.17
  cluster-provision/k8s/1.17/node01.sh
  cluster-provision/k8s/1.17/nodes.sh
  cluster-provision/k8s/1.17/provision.sh
  cluster-provision/k8s/1.17/version
  cluster-provision/k8s/1.18/node01.sh
  cluster-provision/k8s/1.18/nodes.sh
  cluster-provision/k8s/1.18/provision.sh
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/M
