Repository kubevirt/kubevirtci, pull requests merged in 2020-07, with the labels that each got.

#396 Fix check-cluster-up.sh missing Var init
  cluster-provision/k8s/check-cluster-up.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#385 Make provision less sensitive to quay hiccups
  cluster-provision/k8s/1.17/provision.sh
  cluster-provision/k8s/1.18/provision.sh
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#401 Replace bazel with Makefile and bash
  cluster-provision/gocli/.gitignore
  cluster-provision/gocli/BUILD
  cluster-provision/gocli/Makefile
  cluster-provision/gocli/WORKSPACE
  cluster-provision/gocli/build/.dockerignore
  cluster-provision/gocli/build/Dockerfile
  cluster-provision/gocli/cmd/BUILD.bazel
  cluster-provision/gocli/cmd/cli/main.go
  cluster-provision/gocli/cmd/okd/BUILD.bazel
  cluster-provision/gocli/cmd/utils/BUILD.bazel
  cluster-provision/gocli/go.mod
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#400 Bump CNAO to 0.39.2
  cluster-provision/k8s/1.17/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.17/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.18/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.18/manifests/cnao/operator.yaml
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#405 Remove ocp/okd cluster-up
  cluster-up/cluster/images.sh
  cluster-up/cluster/ocp-4.3/README.md
  cluster-up/cluster/ocp-4.3/provider.sh
  cluster-up/cluster/ocp-4.4/README.md
  cluster-up/cluster/ocp-4.4/provider.sh
  cluster-up/cluster/okd-4.1/README.md
  cluster-up/cluster/okd-4.1/provider.sh
  cluster-up/cluster/okd-4.2/README.md
  cluster-up/cluster/okd-4.2/provider.sh
  cluster-up/cluster/okd-4.3/README.md
  cluster-up/cluster/okd-4.3/provider.sh
  cluster-up/container.sh
  cluster-up/ssh.sh
Labels: approved, dco-signoff: yes, lgtm, size/XL

#404 Set default KUBEVIRT_PROVIDER to k8s-1.18.
  cluster-up/hack/common.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#398 Add new maintainers to OWNERS file
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#402 Add update provider hashes make target
  CONTRIBUTING.md
  Makefile
  hack/bump.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#409 Remove ocp provider leftovers
  Makefile
  cluster-up/cluster/openshift-provider-common.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#413 Remove OKD/OCP cluster provision
  OKD.md
  cluster-provision/README.md
  cluster-provision/gocli/cmd/okd/provision.go
  cluster-provision/gocli/cmd/okd/run.go
  cluster-provision/gocli/cmd/provision.go
  cluster-provision/gocli/cmd/run.go
  cluster-provision/manifests/okd/install-config.yaml
  cluster-provision/manifests/okd/local-storage-cr.yaml
  cluster-provision/manifests/okd/local-storage.yaml
  cluster-provision/manifests/okd/registries.conf
  cluster-provision/manifests/okd/registries.yaml
  cluster-provision/ocp/4.3/provision.sh
  cluster-provision/ocp/4.3/publish.sh
  cluster-provision/ocp/4.3/run.sh
  cluster-provision/ocp/4.4/provision.sh
  cluster-provision/ocp/4.4/publish.sh
  cluster-provision/ocp/4.4/run.sh
  cluster-provision/ocp/README.md
  cluster-provision/okd/4.1/provision.sh
  cluster-provision/okd/4.1/publish.sh
  cluster-provision/okd/4.1/run.sh
  cluster-provision/okd/4.2/provision.sh
  cluster-provision/okd/4.2/publish.sh
  cluster-provision/okd/4.2/run.sh
  cluster-provision/okd/4.3/provision.sh
  cluster-provision/okd/4.3/publish.sh
  cluster-provision/okd/4.3/run.sh
  cluster-provision/okd/README.md
  cluster-provision/okd/base/Dockerfile
  cluster-provision/okd/base/build.sh
  cluster-provision/okd/base/entrypoint.sh
  cluster-provision/okd/base/haproxy.cfg
  cluster-provision/okd/base/publish.sh
  cluster-provision/okd/base/vagrant.key
  cluster-provision/okd/hacks/release-4.1
  cluster-provision/okd/hacks/release-4.2
  cluster-provision/okd/hacks/release-4.3
  cluster-provision/okd/hacks/release-4.4
  cluster-provision/okd/scripts/create-local-disks.sh
  cluster-provision/okd/scripts/provision.sh
  cluster-provision/okd/scripts/run.sh
  cluster-up/cluster/images.sh
  pack8s/STATUS.md
  pack8s/cmd/okd/run.go
  pack8s/cmd/run.go
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#423 Remove provisioning of "os" providers
  cluster-provision/README.md
  cluster-provision/common-scripts/images.sh
  cluster-provision/os-3.11-crio/provision.sh
  cluster-provision/os-3.11-crio/publish.sh
  cluster-provision/os-3.11-multus/provision.sh
  cluster-provision/os-3.11-multus/publish.sh
  cluster-provision/os-3.11-multus/scripts/logging.sh
  cluster-provision/os-3.11-multus/scripts/node01.sh
  cluster-provision/os-3.11-multus/scripts/nodes.sh
  cluster-provision/os-3.11-multus/scripts/provision.sh
  cluster-provision/os-3.11/provision.sh
  cluster-provision/os-3.11/publish.sh
  cluster-provision/os-3.11/scripts/logging.sh
  cluster-provision/os-3.11/scripts/node01.sh
  cluster-provision/os-3.11/scripts/nodes.sh
  cluster-provision/os-3.11/scripts/provision.sh
Labels: approved, dco-signoff: yes, lgtm, size/XL

#417 Fix sonobuoy error detection
  hack/conformance.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#419 Refactor calico on K8s 1.18 provider
  cluster-provision/k8s/1.18/manifests/cni.diff
  cluster-provision/k8s/1.18/manifests/cni.do-not-change.yaml
  cluster-provision/k8s/1.18/provision.sh
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#422 Bump calico to 3.15.1 for K8s-1.18
  cluster-provision/k8s/1.18/manifests/cni.diff
  cluster-provision/k8s/1.18/manifests/cni.do-not-change.yaml
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#426 Bump Calico to 3.15.1 on k8s-1.17
  cluster-provision/k8s/1.17/manifests/cni.diff
  cluster-provision/k8s/1.17/manifests/cni.do-not-change.yaml
  cluster-provision/k8s/1.17/manifests/cni.yaml
  cluster-provision/k8s/1.17/provision.sh
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/XXL
