Repository kubevirt/kubevirtci, pull requests merged in 2020-03, with the labels that each got.

#298 Revert "Updated sriov provider"
  cluster-up/cluster/kind-k8s-sriov-1.17.0/README.md
  cluster-up/cluster/kind-k8s-sriov-1.17.0/TROUBLESHOOTING.md
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/csrcreator/certsecret.go
  cluster-up/cluster/kind-k8s-sriov-1.17.0/csrcreator/go.mod
  cluster-up/cluster/kind-k8s-sriov-1.17.0/csrcreator/go.sum
  cluster-up/cluster/kind-k8s-sriov-1.17.0/manifests/multus.yaml
  cluster-up/cluster/kind-k8s-sriov-1.17.0/manifests/network_config_policy.yaml
  cluster-up/cluster/kind-k8s-sriov-1.17.0/provider.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/sriovdp_setup.sh
  cluster-up/cluster/kind/common.sh
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#294 k8s-1.17: Fix non interactive dnf install -y
  cluster-provision/k8s/1.17/provision.sh
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#284 Add kubevirt local testing, reorg sections in separate documents
  K8S.md
  KUBEVIRT_LOCAL_TESTING.md
  OKD.md
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#297 fix kind with ipv6 documentation
  cluster-up/cluster/kind-k8s-1.17.0-ipv6/README.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#302 k8s: Add KUBEVIRT_WITH_CNAO to provision cluster-network-addons-opera…
  cluster-provision/k8s/1.17/manifests/cnao/namespace.yaml
  cluster-provision/k8s/1.17/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.17/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.17/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.17/provision.sh
  cluster-up/cluster/images.sh
  cluster-up/cluster/k8s-1.17/README.md
  cluster-up/cluster/k8s-provider-common.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#303 k8s-1.17: Wait for transient hostname
  cluster-provision/k8s/1.17/node01.sh
  cluster-provision/k8s/1.17/nodes.sh
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#306 Add dbelenky to owners file
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#304 Fix ocp 4.3 provider by updating patch file, reprovison
  cluster-provision/okd/hacks/release-4.3
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#307 Add most used commands to wrapper
  cluster-up/kubectl.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#310 Upgrade CNAO to 0.31.0
  cluster-provision/k8s/1.17/manifests/cnao/operator.yaml
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#311 Enable SELinux for Docker in provision.sh for k8s 1.17
  cluster-provision/k8s/1.17/provision.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#199 Fix external provider for openshift-ci usage
  cluster-up/cluster/external/provider.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#312 Bump k8s 1.17 cnao to 0.32.0
  cluster-provision/k8s/1.17/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.17/manifests/cnao/operator.yaml
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#314 Fix call to provision.sh in local testing docs
  KUBEVIRT_LOCAL_TESTING.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#315 Validate cluster nodes labels and taints in kind providers
  cluster-up/cluster/kind/common.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#316 Activate cpumanager at kind workers
  cluster-up/cluster/kind/common.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#322 add local registry mirror to kind base
  cluster-up/cluster/kind/manifests/kind.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#319 kind: fix SR-IOV 1.17 provider
  cluster-up/cluster/kind-k8s-sriov-1.14.2/README.md
  cluster-up/cluster/kind-k8s-sriov-1.14.2/TROUBLESHOOTING.md
  cluster-up/cluster/kind-k8s-sriov-1.14.2/config_sriov.sh
  cluster-up/cluster/kind-k8s-sriov-1.14.2/manifests/kube-flannel.yaml
  cluster-up/cluster/kind-k8s-sriov-1.14.2/manifests/multus.yaml
  cluster-up/cluster/kind-k8s-sriov-1.14.2/manifests/network_config_policy.yaml
  cluster-up/cluster/kind-k8s-sriov-1.14.2/provider.sh
  cluster-up/cluster/kind-k8s-sriov-1.14.2/sriovdp_setup.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/TROUBLESHOOTING.md
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/provider.sh
  cluster-up/cluster/kind/README.md
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#301 Fix OCP-4.4 provision
  cluster-provision/okd/hacks/release-4.4
  cluster-provision/okd/scripts/provision.sh
  cluster-provision/okd/scripts/run.sh
  cluster-up/cluster/images.sh
  cluster-up/cluster/ocp-4.4/README.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#317 kind: Don't relabel nodes with with schedule=true if not needed
  cluster-up/cluster/kind/common.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#323 kind: deploy local volume provisioner
  cluster-up/cluster/kind-k8s-1.17.0-ipv6/provider.sh
  cluster-up/cluster/kind/manifests/local-volume.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#326 kind: remove tty/interactive when deploying the local provisioner
  cluster-up/cluster/kind-k8s-1.17.0-ipv6/provider.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#321 enable selinux for 1.17 provider
  cluster-provision/k8s/1.17/manifests/cni.yaml
  cluster-provision/k8s/1.17/node01.sh
  cluster-provision/k8s/1.17/provision.sh
  cluster-provision/k8s/1.17/version
Labels: approved, dco-signoff: yes, lgtm, size/M

#327 Label k8s non master nodes as workers
  cluster-up/cluster/k8s-provider-common.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#325 drop genie provider
  cluster-provision/README.md
  cluster-provision/k8s-genie/1.11.1/README.md
  cluster-provision/k8s-genie/1.11.1/provision.sh
  cluster-provision/k8s-genie/1.11.1/publish.sh
  cluster-provision/k8s-genie/provision.sh
  cluster-provision/k8s-genie/publish.sh
  cluster-provision/k8s-genie/scripts/node01.sh
  cluster-provision/k8s-genie/scripts/nodes.sh
  cluster-provision/k8s-genie/scripts/provision.sh
  cluster-provision/manifests/genie.yaml
  cluster-up/cluster/images.sh
  cluster-up/cluster/k8s-genie-1.11.1/README.md
  cluster-up/cluster/k8s-genie-1.11.1/provider.sh
  pack8s/STATUS.md
Labels: approved, dco-signoff: yes, lgtm, size/XL
