Repository kubevirt/kubevirtci, pull requests merged in 2020-12, with the labels that each got.

#497 Bump Z versions of k8s clusters
  cluster-provision/k8s/1.17/conformance.json
  cluster-provision/k8s/1.17/version
  cluster-provision/k8s/1.18/conformance.json
  cluster-provision/k8s/1.18/version
  cluster-provision/k8s/1.19/conformance.json
  cluster-provision/k8s/1.19/provision.sh
  cluster-provision/k8s/1.19/version
  hack/conformance.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#492 SRIOV Provider fine tunes: Simplify Readiness Checks
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#498 Move etcd on k8s-1.19 to in-memory storage
  cluster-provision/k8s/1.19/node01.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#496 Add k8s provider for 1.20
  cluster-provision/k8s/1.20/base
  cluster-provision/k8s/1.20/bind_device_to_vfio.sh
  cluster-provision/k8s/1.20/ceph-csi.sh
  cluster-provision/k8s/1.20/conformance.json
  cluster-provision/k8s/1.20/logging.sh
  cluster-provision/k8s/1.20/manifests/ceph/ceph-secret.yaml
  cluster-provision/k8s/1.20/manifests/ceph/ceph-snapshotclass.yaml
  cluster-provision/k8s/1.20/manifests/ceph/ceph-storageclass.yaml
  cluster-provision/k8s/1.20/manifests/ceph/csi-attacher-rbac.yaml
  cluster-provision/k8s/1.20/manifests/ceph/csi-nodeplugin-rbac.yaml
  cluster-provision/k8s/1.20/manifests/ceph/csi-provisioner-rbac.yaml
  cluster-provision/k8s/1.20/manifests/ceph/csi-rbdplugin-attacher.yaml
  cluster-provision/k8s/1.20/manifests/ceph/csi-rbdplugin-provisioner.yaml
  cluster-provision/k8s/1.20/manifests/ceph/csi-rbdplugin.yaml
  cluster-provision/k8s/1.20/manifests/cnao/namespace.yaml
  cluster-provision/k8s/1.20/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.20/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.20/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.20/manifests/cni.diff
  cluster-provision/k8s/1.20/manifests/cni.do-not-change.yaml
  cluster-provision/k8s/1.20/manifests/kubeadm.conf
  cluster-provision/k8s/1.20/manifests/local-volume.yaml
  cluster-provision/k8s/1.20/manifests/logging.yaml
  cluster-provision/k8s/1.20/node01.sh
  cluster-provision/k8s/1.20/nodes.sh
  cluster-provision/k8s/1.20/provision.sh
  cluster-provision/k8s/1.20/version
  cluster-up/cluster/k8s-1.20/README.md
  cluster-up/cluster/k8s-1.20/dev-guide.md
  cluster-up/cluster/k8s-1.20/provider.sh
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#501 sriov, Refactor movement of sriov PFs to the network namespace
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
Labels: approved, dco-signoff: yes, lgtm, size/M
