Repository kubevirt/kubevirtci, pull requests merged in 2020-09, with the labels that each got.

#436 Change the pre-provisioned path on the K8s nodes
  cluster-provision/k8s/1.16/provision.sh
  cluster-provision/k8s/1.17/provision.sh
  cluster-provision/k8s/1.18/provision.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#438 Update kubevirtci images to latest digest
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#434 Add k8s 1.19 provider
  cluster-provision/k8s/1.19/base
  cluster-provision/k8s/1.19/ceph-csi.sh
  cluster-provision/k8s/1.19/conformance.json
  cluster-provision/k8s/1.19/logging.sh
  cluster-provision/k8s/1.19/manifests/ceph/ceph-secret.yaml
  cluster-provision/k8s/1.19/manifests/ceph/ceph-snapshotclass.yaml
  cluster-provision/k8s/1.19/manifests/ceph/ceph-storageclass.yaml
  cluster-provision/k8s/1.19/manifests/ceph/csi-attacher-rbac.yaml
  cluster-provision/k8s/1.19/manifests/ceph/csi-nodeplugin-rbac.yaml
  cluster-provision/k8s/1.19/manifests/ceph/csi-provisioner-rbac.yaml
  cluster-provision/k8s/1.19/manifests/ceph/csi-rbdplugin-attacher.yaml
  cluster-provision/k8s/1.19/manifests/ceph/csi-rbdplugin-provisioner.yaml
  cluster-provision/k8s/1.19/manifests/ceph/csi-rbdplugin.yaml
  cluster-provision/k8s/1.19/manifests/cnao/namespace.yaml
  cluster-provision/k8s/1.19/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.19/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.19/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.19/manifests/cni.diff
  cluster-provision/k8s/1.19/manifests/cni.do-not-change.yaml
  cluster-provision/k8s/1.19/manifests/kubeadm.conf
  cluster-provision/k8s/1.19/manifests/local-volume.yaml
  cluster-provision/k8s/1.19/manifests/logging.yaml
  cluster-provision/k8s/1.19/node01.sh
  cluster-provision/k8s/1.19/nodes.sh
  cluster-provision/k8s/1.19/provision.sh
  cluster-provision/k8s/1.19/version
  cluster-up/cluster/images.sh
  cluster-up/cluster/k8s-1.19/README.md
  cluster-up/cluster/k8s-1.19/dev-guide.md
  cluster-up/cluster/k8s-1.19/provider.sh
  hack/conformance.sh
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#392 [2] k8s1.18: Add provision script to update kernel args
  cluster-provision/k8s/1.18/kargs.sh
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#443 Disable endpointslices
  cluster-provision/k8s/1.19/manifests/kubeadm.conf
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#428 vm-image-builder: Automate creating customized Kubevirt VM's images
  cluster-provision/images/vm-image-builder/Dockerfile.containerdisk
  cluster-provision/images/vm-image-builder/OWNERS
  cluster-provision/images/vm-image-builder/README.md
  cluster-provision/images/vm-image-builder/build-containerdisk.sh
  cluster-provision/images/vm-image-builder/create-containerdisk.sh
  cluster-provision/images/vm-image-builder/customize-image.sh
  cluster-provision/images/vm-image-builder/example/cloud-config
  cluster-provision/images/vm-image-builder/example/image-url
  cluster-provision/images/vm-image-builder/fedora-sriov-lane/cloud-config
  cluster-provision/images/vm-image-builder/fedora-sriov-lane/image-url
  cluster-provision/images/vm-image-builder/publish-containerdisk.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#445 dnsmasq: Mount /lib/modules to use ip6tables
  cluster-provision/cli/cli
  cluster-provision/gocli/cmd/run.go
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#446 Mount /lib/modules at gocli if exists
  cluster-provision/cli/cli
  cluster-provision/gocli/cmd/run.go
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#444 Don't create pre-provisioend configs at root
  cluster-provision/k8s/1.17/node01.sh
  cluster-provision/k8s/1.17/provision.sh
  cluster-provision/k8s/1.18/node01.sh
  cluster-provision/k8s/1.18/provision.sh
  cluster-up/cluster/images.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#448 Install iptables at k8s provision for docker-ce providers
  cluster-provision/k8s/1.17/provision.sh
  cluster-provision/k8s/1.18/provision.sh
  cluster-provision/k8s/1.19/provision.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#435 Store digests into gocli binary
  CONTRIBUTING.md
  cluster-provision/gocli/Makefile
  cluster-provision/gocli/cmd/run.go
  cluster-provision/gocli/images.json
  cluster-provision/gocli/images/images.go
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/images.sh
  hack/bump.sh
Labels: approved, dco-signoff: yes, lgtm, size/L
