Repository kubevirt/kubevirtci, pull requests merged in 2020-10, with the labels that each got.

#449 Bump k8s-1.19 nm to 1.22.8
  cluster-provision/gocli/images.json
  cluster-provision/k8s/1.19/provision.sh
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#440 GoCli: Expose ports 80 and 443
  cluster-provision/centos7/scripts/vm.sh
  cluster-provision/centos8/scripts/vm.sh
  cluster-provision/cli/cli
  cluster-provision/fedora/scripts/vm.sh
  cluster-provision/gocli/cmd/ports.go
  cluster-provision/gocli/cmd/run.go
  cluster-provision/gocli/cmd/utils/ports.go
  cluster-provision/gocli/images.json
  cluster-provision/k8s/1.17/base
  cluster-provision/k8s/1.18/base
  cluster-provision/k8s/1.19/base
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/hack/common.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#447 Emulate krew integration for virtctl.sh in our dev environment
  cluster-up/kubectl.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#451 Revert http and https port to randomized
  cluster-up/hack/common.sh
Labels: approved, lgtm, size/XS

#453 Make KUBEVIRTCI_TAG requirement explicit
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#454 Use latest gocli if non specified at `make cluster-up`
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#437 add an option to assign a GPU to a kubevirtci node
  cluster-provision/centos8/scripts/vm.sh
  cluster-provision/gocli/cmd/run.go
  cluster-provision/k8s/1.14/bind_device_to_vfio.sh
  cluster-provision/k8s/1.15/bind_device_to_vfio.sh
  cluster-provision/k8s/1.16/bind_device_to_vfio.sh
  cluster-provision/k8s/1.17/bind_device_to_vfio.sh
  cluster-provision/k8s/1.17/provision.sh
  cluster-provision/k8s/1.18/bind_device_to_vfio.sh
  cluster-provision/k8s/1.18/provision.sh
  cluster-provision/k8s/1.19/bind_device_to_vfio.sh
  cluster-provision/k8s/1.19/provision.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#455 Remove unwanted traces from older clusters
  cluster-provision/k8s/1.14/bind_device_to_vfio.sh
  cluster-provision/k8s/1.15/bind_device_to_vfio.sh
  cluster-provision/k8s/1.16/bind_device_to_vfio.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#456 Add cluster-up SRIOV *.cert to gitignore
  cluster-up/.gitignore
Labels: approved, dco-signoff: yes, lgtm, size/XS

#458 Enable docker-ce-nightly repos to get newer containerd
  cluster-provision/k8s/1.17/provision.sh
  cluster-provision/k8s/1.18/provision.sh
  cluster-provision/k8s/1.19/provision.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#460 run: Move container create to the correct place
  cluster-provision/gocli/cmd/run.go
  cluster-provision/k8s/check-cluster-up.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#459 Fix SRIOV lane: configure CNI MTU according to the CRI bridge MTU on KIND infra
  cluster-up/cluster/kind/common.sh
  cluster-up/cluster/kind/manifests/kube-calico.diff.in
  cluster-up/cluster/kind/manifests/kube-calico.yaml.in
  cluster-up/cluster/kind/manifests/kube-flannel.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XL

#463 Remove kind ipv6 provider
  cluster-up/cluster/kind-k8s-1.17.0-ipv6/README.md
  cluster-up/cluster/kind-k8s-1.17.0-ipv6/provider.sh
  cluster-up/cluster/kind/common.sh
  cluster-up/cluster/kind/manifests/kind-ipv6.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#465 Try to cope with initial unresponsiveness of ssh
  cluster-provision/gocli/cmd/run.go
Labels: approved, dco-signoff: yes, lgtm, size/S
