Repository kubevirt/kubevirtci, pull requests merged in 2021-11, with the labels that each got.

#697 Do not declare disk mount for node container
  cluster-provision/gocli/cmd/run.go
Labels: size/S, approved, lgtm, dco-signoff: yes

#702 Use kustomize to patch ip reconciler job, applying a label for filtering
  cluster-provision/k8s/1.19/manifests/whereabouts/daemonset-install.yaml
  cluster-provision/k8s/1.19/manifests/whereabouts/ip-reconciler-job.yaml
  cluster-provision/k8s/1.19/manifests/whereabouts/whereabouts-v0.5.yaml
  cluster-provision/k8s/1.19/manifests/whereabouts/whereabouts.cni.cncf.io_ippools.yaml
  cluster-provision/k8s/1.19/manifests/whereabouts/whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml
  cluster-provision/k8s/1.20/manifests/whereabouts/daemonset-install.yaml
  cluster-provision/k8s/1.20/manifests/whereabouts/ip-reconciler-job.yaml
  cluster-provision/k8s/1.20/manifests/whereabouts/whereabouts-v0.5.yaml
  cluster-provision/k8s/1.20/manifests/whereabouts/whereabouts.cni.cncf.io_ippools.yaml
  cluster-provision/k8s/1.20/manifests/whereabouts/whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml
  cluster-provision/k8s/1.21/manifests/whereabouts/daemonset-install.yaml
  cluster-provision/k8s/1.21/manifests/whereabouts/ip-reconciler-job.yaml
  cluster-provision/k8s/1.21/manifests/whereabouts/whereabouts-v0.5.yaml
  cluster-provision/k8s/1.21/manifests/whereabouts/whereabouts.cni.cncf.io_ippools.yaml
  cluster-provision/k8s/1.21/manifests/whereabouts/whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml
  cluster-provision/k8s/1.22/manifests/whereabouts/daemonset-install.yaml
  cluster-provision/k8s/1.22/manifests/whereabouts/ip-reconciler-job.yaml
  cluster-provision/k8s/1.22/manifests/whereabouts/whereabouts-v0.5.yaml
  cluster-provision/k8s/1.22/manifests/whereabouts/whereabouts.cni.cncf.io_ippools.yaml
  cluster-provision/k8s/1.22/manifests/whereabouts/whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml
  cluster-provision/k8s/check-cluster-up.sh
  hack/bump-whereabouts.sh
  hack/kustomization/whereabouts/kustomization.yaml
  hack/kustomization/whereabouts/patch-ip-reconciler-job.yaml
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#701 Use configured kubectl instead of one in PATH
  cluster-provision/centos8/scripts/vm.sh
  cluster-up/cluster/k8s-provider-common.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#706 Fix deploy-manifests by excluding ip-reconciler pod from ready check
  cluster-provision/k8s/deploy-manifests.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#704 network, multus: remove multus delegate config
  cluster-up/cluster/kind-1.19-sriov/sriov-components/manifests/multus.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/multus.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#703 Add registry volume during provision
  cluster-provision/gocli/cmd/provision.go
  cluster-provision/gocli/cmd/run.go
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#711 Add fedora kubeadm image for capk
  cluster-provision/images/vm-image-builder/fedora-kubeadm/cloud-config
  cluster-provision/images/vm-image-builder/fedora-kubeadm/image-url
  cluster-provision/images/vm-image-builder/fedora-kubeadm/os-variant
Labels: size/M, approved, lgtm, dco-signoff: yes

#708 vgpu, Remove podpreset
  cluster-up/cluster/kind-1.19-vgpu/provider.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#714 k8s-1.2x, provision: mv original cni manifest
  cluster-provision/k8s/1.20/provision.sh
  cluster-provision/k8s/1.21/provision.sh
  cluster-provision/k8s/1.22/provision.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes
