Repository kubevirt/kubevirtci, pull requests merged in 2021-01, with the labels that each got.

#514 Revert "Move etd on k8s-1.19 to in-memory storage (#498)"
  cluster-provision/k8s/1.19/node01.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#517 Don't run etcd on memory by default
  cluster-provision/gocli/cmd/run.go
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#513 sriov, Fix VFs allocation race condition of sriov operator
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#475 sriov, create sriov OWNERS file
  cluster-up/cluster/kind-k8s-sriov-1.17.0/OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/S

#505 Use cluster container images from quay.io by default
  cluster-provision/centos8/build.sh
  cluster-provision/gocli/Makefile
  cluster-provision/gocli/cmd/provision.go
  cluster-provision/gocli/cmd/run.go
  cluster-provision/gocli/docker/docker.go
  cluster-provision/images/kubevirt-testing/publish.sh
  cluster-provision/k8s/check-cluster-up.sh
  cluster-up/cluster/ephemeral-provider-common.sh
  publish.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#521 allow specifying a custom image repo for gocli
  cluster-provision/gocli/Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#525 Fix gocli image publication
  hack/conformance.sh
  publish.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#530 Fedora image with test tooling pre-configured
  cluster-provision/images/vm-image-builder/fedora-with-test-tooling/cloud-config
  cluster-provision/images/vm-image-builder/fedora-with-test-tooling/image-url
Labels: approved, dco-signoff: yes, lgtm, size/S

#529 Fix provider image tag
  publish.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#510 sriov, Assign only one PF for the worker
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#470 SRIOV provider fine tunes: Logs and Missing Configurations
  Makefile
  cluster-up/cluster/kind-k8s-sriov-1.17.0/provider.sh
  cluster-up/cluster/kind/common.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#537 Subject: [PATCH] enable kind cluster-up works on multi-arch
  cluster-up/cluster/kind/common.sh
Labels: approved, dco-signoff: yes, lgtm, size/S
