Repository kubevirt/kubevirtci, pull requests merged in 2021-06, with the labels that each got.

#614 Expose prometheus and grafana via nodeports
  cluster-provision/gocli/cmd/utils/ports.go
  cluster-provision/k8s/1.21/manifests/nodeports/monitoring.yaml
  cluster-provision/k8s/1.21/prometheus.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#613 Add a Dockerfile for kernel-boot container used for testing
  cluster-provision/images/kubevirt-testing/kernel-boot-container/Dockerfile.alpine-ext-kernel-boot-demo
Labels: approved, dco-signoff: yes, lgtm, size/XS

#618 Asking to be added as an approver
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#620 Fix 1.21 provider: Move fetch-images.sh into provision folder
  cluster-provision/k8s/1.21/fetch-images.sh
  cluster-provision/k8s/README.md
  cluster-provision/k8s/check-pod-images.sh
  cluster-provision/k8s/provision.sh
  cluster-provision/k8s/validate-pod-pull-policies.sh
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#621 SRIOV provider: Bump nodes image to k8s-1.19
  cluster-up/cluster/kind-1.19-sriov/OWNERS
  cluster-up/cluster/kind-1.19-sriov/README.md
  cluster-up/cluster/kind-1.19-sriov/TROUBLESHOOTING.md
  cluster-up/cluster/kind-1.19-sriov/certcreator/certlib/selfsign.go
  cluster-up/cluster/kind-1.19-sriov/certcreator/certsecret.go
  cluster-up/cluster/kind-1.19-sriov/certcreator/go.mod
  cluster-up/cluster/kind-1.19-sriov/certcreator/go.sum
  cluster-up/cluster/kind-1.19-sriov/config_sriov_cluster.sh
  cluster-up/cluster/kind-1.19-sriov/manifests/network_config_policy.yaml
  cluster-up/cluster/kind-1.19-sriov/provider.sh
  cluster-up/cluster/kind-1.19-sriov/sriov-components/manifests/kustomization.yaml
  cluster-up/cluster/kind-1.19-sriov/sriov-components/manifests/multus.yaml
  cluster-up/cluster/kind-1.19-sriov/sriov-components/manifests/patch-node-selector.yaml.in
  cluster-up/cluster/kind-1.19-sriov/sriov-components/manifests/patch-sriovdp-resource-prefix.yaml.in
  cluster-up/cluster/kind-1.19-sriov/sriov-components/manifests/sriov-cni-daemonset.yaml
  cluster-up/cluster/kind-1.19-sriov/sriov-components/manifests/sriov-ns.yaml
  cluster-up/cluster/kind-1.19-sriov/sriov-components/manifests/sriovdp-config.yaml.in
  cluster-up/cluster/kind-1.19-sriov/sriov-components/manifests/sriovdp-daemonset.yaml
  cluster-up/cluster/kind-1.19-sriov/sriov-components/sriov_components.sh
  cluster-up/cluster/kind-1.19-sriov/sriov-node/configure_vfs.sh
  cluster-up/cluster/kind-1.19-sriov/sriov-node/node.sh
  cluster-up/cluster/kind-1.19-sriov/sriov_operator.sh
  cluster-up/cluster/kind-1.19-sriov/sriovdp_setup.sh
  cluster-up/cluster/kind/common.sh
  cluster-up/cluster/kind/podpreset.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#624 Use alternative registry on conformance tests
  hack/conformance.sh
  hack/confromance-image-config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#626 cnao, provision, Bump k8s-1.19/1.20/1.21 cnao to v0.56.0
  cluster-provision/k8s/1.19/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.20/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.21/manifests/cnao/operator.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#593 Switch to booting via kernel and initrd from outside the image
  cluster-provision/centos8/Dockerfile
  cluster-provision/centos8/scripts/additional.kernel.args
  cluster-provision/centos8/scripts/kernel.args
  cluster-provision/centos8/scripts/vm.sh
  cluster-provision/gocli/cmd/provision.go
  cluster-provision/gocli/cmd/run.go
  cluster-provision/gocli/go.mod
  cluster-provision/gocli/go.sum
  cluster-provision/gocli/vendor/github.com/alessio/shellescape/.gitignore
  cluster-provision/gocli/vendor/github.com/alessio/shellescape/.golangci.yml
  cluster-provision/gocli/vendor/github.com/alessio/shellescape/.goreleaser.yml
  cluster-provision/gocli/vendor/github.com/alessio/shellescape/AUTHORS
  cluster-provision/gocli/vendor/github.com/alessio/shellescape/CODE_OF_CONDUCT.md
  cluster-provision/gocli/vendor/github.com/alessio/shellescape/LICENSE
  cluster-provision/gocli/vendor/github.com/alessio/shellescape/README.md
  cluster-provision/gocli/vendor/github.com/alessio/shellescape/go.mod
  cluster-provision/gocli/vendor/github.com/alessio/shellescape/shellescape.go
  cluster-provision/gocli/vendor/modules.txt
  cluster-provision/k8s/1.17/kargs.sh
  cluster-provision/k8s/1.17/provision.sh
  cluster-provision/k8s/1.18/kargs.sh
  cluster-provision/k8s/1.18/provision.sh
  cluster-provision/k8s/1.19/provision.sh
  cluster-provision/k8s/1.20/provision.sh
  cluster-provision/k8s/1.21/provision.sh
  cluster-up/cluster/k8s-1.21-cgroupsv2/README.md
  cluster-up/cluster/k8s-1.21-cgroupsv2/provider.sh
  cluster-up/cluster/k8s-provider-common.sh
Labels: approved, dco-signoff: yes, lgtm, size/XL

#628 Send a few info logs to stderr instead of stdout
  cluster-provision/k8s/check-pod-images.sh
  cluster-provision/k8s/validate-pod-pull-policies.sh
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#630 Switch the default to k8s-1.20
  cluster-up/hack/common.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#616 certcreator/certsecret: fix misspell for sucessfully
  cluster-up/cluster/kind-1.19-sriov/certcreator/certsecret.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#629 Configure cgroup v2 settings on cluster-up
  cluster-provision/gocli/cmd/provision.go
  cluster-provision/k8s/1.20/node01.sh
  cluster-provision/k8s/1.20/nodes.sh
  cluster-provision/k8s/1.20/provision.sh
  cluster-provision/k8s/1.21/node01.sh
  cluster-provision/k8s/1.21/nodes.sh
  cluster-provision/k8s/1.21/provision.sh
  cluster-provision/k8s/provision.sh
  cluster-up/cluster/k8s-1.20-cgroupsv2/provider.sh
  cluster-up/cluster/k8s-1.21-cgroupsv2/provider.sh
  publish.sh
Labels: approved, dco-signoff: yes, lgtm, size/L
