Repository kubevirt/kubevirtci, pull requests merged in 2021-07, with the labels that each got.

#637 Add 'stress' tool SRIOV Lane Containerdisk
  cluster-provision/images/vm-image-builder/fedora-sriov-lane/cloud-config
Labels: approved, dco-signoff: yes, lgtm, size/XS

#633 istio, Add assertion that istio deployment succeeded
  cluster-up/cluster/k8s-provider-common.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#636 Adding support for sysprep func test
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#638 Restore provision checking for cgroupsv2 lanes
  cluster-provision/k8s/check-cluster-up.sh
  cluster-provision/k8s/provision.sh
  cluster-up/cluster/k8s-1.20-cgroupsv2/README.md
  cluster-up/cluster/k8s-1.20-cgroupsv2/provider.sh
  cluster-up/cluster/k8s-1.20/README.md
  cluster-up/cluster/k8s-1.20/provider.sh
  cluster-up/cluster/k8s-1.21-cgroupsv2/README.md
  cluster-up/cluster/k8s-1.21-cgroupsv2/provider.sh
  cluster-up/cluster/k8s-1.21/README.md
  cluster-up/cluster/k8s-1.21/provider.sh
  cluster-up/hack/common.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#632 Istio: Download istioctl binary from gcp mirror
  cluster-provision/k8s/1.20/istio.sh
  cluster-provision/k8s/1.20/provision.sh
  cluster-provision/k8s/1.21/istio.sh
  cluster-provision/k8s/1.21/provision.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#639 Update prerequisites for vm-image-builder
  cluster-provision/images/vm-image-builder/README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#646 [Sig-Scale] add Grafana dashboard for kubevirt control plane
  cluster-provision/k8s/1.21/manifests/prometheus/README.md
  cluster-provision/k8s/1.21/manifests/prometheus/grafana/grafana-dashboardDefinitions.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#623 Generate random product_uuid at qemu nodes
  cluster-provision/centos8/scripts/vm.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#649 sriov, Add info about VFs mapping and PFs PCI addresses
  cluster-up/cluster/kind-1.19-sriov/provider.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#650 Remove cluster-provision/manifests
  cluster-provision/manifests/README.md
  cluster-provision/manifests/ceph/ceph-secret.yaml
  cluster-provision/manifests/ceph/ceph-snapshotclass.yaml
  cluster-provision/manifests/ceph/ceph-storageclass.yaml
  cluster-provision/manifests/ceph/csi-attacher-rbac.yaml
  cluster-provision/manifests/ceph/csi-nodeplugin-rbac.yaml
  cluster-provision/manifests/ceph/csi-provisioner-rbac.yaml
  cluster-provision/manifests/ceph/csi-rbdplugin-attacher.yaml
  cluster-provision/manifests/ceph/csi-rbdplugin-provisioner.yaml
  cluster-provision/manifests/ceph/csi-rbdplugin.yaml
  cluster-provision/manifests/cni-plugins-ds.yaml
  cluster-provision/manifests/cni/calico/manifest.yaml
  cluster-provision/manifests/cni/calico/script.d/001-nm-filter-calico-ifaces.sh
  cluster-provision/manifests/cni/calico/script.d/002-allow-ip-forwarding.sh
  cluster-provision/manifests/cni/calico/script.d/003-change-cidr.sh
  cluster-provision/manifests/cni/flannel-ge-12.yaml
  cluster-provision/manifests/cni/flannel-ge-16.yaml
  cluster-provision/manifests/cni/flannel.yaml
  cluster-provision/manifests/kubernetes-multus.yaml
  cluster-provision/manifests/kubernetes-ovs-cni.yaml
  cluster-provision/manifests/local-volume-ge-16.yaml
  cluster-provision/manifests/local-volume.yaml
  cluster-provision/manifests/logging.yaml
  cluster-provision/manifests/multus.yaml
  cluster-provision/manifests/openshift-multus.yaml
  cluster-provision/manifests/openshift-ovs-cni.yaml
  cluster-provision/manifests/static-ptp-conf.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XXL
