Repository kubevirt/kubevirtci, pull requests merged in 2021-09, with the labels that each got.

#673 Move kubevirtci k8s startup and dev guide to parent dir
  cluster-up/cluster/K8S.md
  cluster-up/cluster/K8S_AUTOMATION.md
  cluster-up/cluster/K8S_DEV_GUIDE.md
  cluster-up/cluster/k8s-1.19/README.md
  cluster-up/cluster/k8s-1.19/dev-guide.md
  cluster-up/cluster/k8s-1.20/README.md
  cluster-up/cluster/k8s-1.20/dev-guide.md
Labels: size/XL, approved, lgtm, dco-signoff: yes

#675 Fix a race in the scp calls
  cluster-provision/gocli/cmd/scp.go
Labels: size/S, approved, lgtm, dco-signoff: yes

#672 Add setup to emulate NVMe device
  cluster-provision/centos8/scripts/vm.sh
  cluster-provision/gocli/cmd/run.go
Labels: size/S, approved, lgtm, dco-signoff: yes

#667 Update instruction to use K8s 1.21 since 1.16 already been deprecated.
  K8S.md
  cluster-up/README.md
Labels: size/S, ok-to-test, approved, lgtm, dco-signoff: yes

#677 Adjust KCI for k8s-1.22 provider
  cluster-provision/k8s/1.22/manifests/kubeadm.conf
  cluster-provision/k8s/1.22/provision.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#671 cluster-provision: add whereabouts manifests and image to k8s lanes 1.19 and 1.20
  cluster-provision/k8s/1.19/manifests/whereabouts/daemonset-install.yaml
  cluster-provision/k8s/1.19/manifests/whereabouts/ip-reconciler-job.yaml
  cluster-provision/k8s/1.19/manifests/whereabouts/whereabouts.cni.cncf.io_ippools.yaml
  cluster-provision/k8s/1.19/manifests/whereabouts/whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml
  cluster-provision/k8s/1.19/provision.sh
  cluster-provision/k8s/1.20/manifests/whereabouts/daemonset-install.yaml
  cluster-provision/k8s/1.20/manifests/whereabouts/ip-reconciler-job.yaml
  cluster-provision/k8s/1.20/manifests/whereabouts/whereabouts.cni.cncf.io_ippools.yaml
  cluster-provision/k8s/1.20/manifests/whereabouts/whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml
  cluster-provision/k8s/1.20/provision.sh
  cluster-provision/k8s/1.21/manifests/whereabouts/daemonset-install.yaml
  cluster-provision/k8s/1.21/manifests/whereabouts/ip-reconciler-job.yaml
  cluster-provision/k8s/1.21/manifests/whereabouts/whereabouts.cni.cncf.io_ippools.yaml
  cluster-provision/k8s/1.21/manifests/whereabouts/whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml
  cluster-provision/k8s/1.21/provision.sh
  cluster-up/cluster/k8s-provider-common.sh
  hack/bump-whereabouts.sh
Labels: size/XL, approved, lgtm, dco-signoff: yes

#681 whereabouts: add to 1.22 lane
  cluster-provision/k8s/1.22/manifests/whereabouts/daemonset-install.yaml
  cluster-provision/k8s/1.22/manifests/whereabouts/ip-reconciler-job.yaml
  cluster-provision/k8s/1.22/manifests/whereabouts/whereabouts.cni.cncf.io_ippools.yaml
  cluster-provision/k8s/1.22/manifests/whereabouts/whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml
  cluster-provision/k8s/1.22/provision.sh
Labels: size/L, approved, lgtm, dco-signoff: yes

#680 Add support for realtime tuning kernel arguments
  cluster-provision/centos8/scripts/kernel.args
  cluster-provision/gocli/cmd/run.go
  cluster-provision/k8s/1.19/node01.sh
  cluster-provision/k8s/1.19/nodes.sh
  cluster-provision/k8s/1.20/node01.sh
  cluster-provision/k8s/1.20/nodes.sh
  cluster-provision/k8s/1.21/node01.sh
  cluster-provision/k8s/1.21/nodes.sh
  cluster-provision/k8s/1.22/node01.sh
  cluster-provision/k8s/1.22/nodes.sh
  cluster-provision/k8s/1.22/realtime.sh
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#679 Use container registry from Quay
  cluster-provision/gocli/cmd/utils/images.go
Labels: size/XS, approved, lgtm, dco-signoff: yes

#685 Use calico images from Quay
  cluster-provision/k8s/1.19/manifests/cni.diff
  cluster-provision/k8s/1.20/manifests/cni.diff
  cluster-provision/k8s/1.21/extra-pre-pull-images
  cluster-provision/k8s/1.21/manifests/cni.diff
  cluster-provision/k8s/1.22/extra-pre-pull-images
  cluster-provision/k8s/1.22/manifests/cni.diff
Labels: size/L, approved, lgtm, dco-signoff: yes

#676 Add cdi deployment to kubevirtci clusters
  cluster-provision/k8s/1.19/manifests/cdi-1.36.0-cr.yaml
  cluster-provision/k8s/1.19/manifests/cdi-1.36.0-operator.yaml
  cluster-provision/k8s/1.19/provision.sh
  cluster-provision/k8s/1.20/manifests/cdi-1.36.0-cr.yaml
  cluster-provision/k8s/1.20/manifests/cdi-1.36.0-operator.yaml
  cluster-provision/k8s/1.20/provision.sh
  cluster-provision/k8s/1.21/manifests/cdi-1.37.1-cr.yaml
  cluster-provision/k8s/1.21/manifests/cdi-1.37.1-operator.yaml
  cluster-provision/k8s/1.21/provision.sh
  cluster-provision/k8s/1.22/manifests/cdi-1.37.1-cr.yaml
  cluster-provision/k8s/1.22/manifests/cdi-1.37.1-operator.yaml
  cluster-provision/k8s/1.22/provision.sh
  cluster-provision/k8s/check-cluster-up.sh
  cluster-provision/k8s/deploy-manifests.sh
  cluster-provision/k8s/fetch-latest-cdi.sh
  cluster-up/cluster/k8s-provider-common.sh
  cluster-up/hack/common.sh
Labels: size/L, approved, lgtm, dco-signoff: yes

#684 Simplify hugepages flags in gocli
  cluster-provision/gocli/cmd/run.go
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#665 CNV-13187: Create new fedora-realtime container disk for realtime testing
  cluster-provision/images/vm-image-builder/fedora-realtime/cloud-config
  cluster-provision/images/vm-image-builder/fedora-realtime/image-url
  cluster-provision/images/vm-image-builder/fedora-realtime/os-variant
Labels: size/M, approved, lgtm, dco-signoff: yes

#687 Move logic to enable realtime scheduling on all nodes
  cluster-provision/gocli/cmd/run.go
Labels: size/S, approved, lgtm, dco-signoff: yes
