Repository kubevirt/kubevirtci, pull requests merged in 2021-05, with the labels that each got.

#603 cnao, provision, Remove unneeded manfiests
  cluster-provision/manifests/cna/namespace.yaml
  cluster-provision/manifests/cna/network-addons-config-example.cr.yaml
  cluster-provision/manifests/cna/network-addons-config.crd.yaml
  cluster-provision/manifests/cna/operator.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#604 cnao, Create bump cnao on kubevirtci script
  hack/bump-cnao.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#607 Fix rsync command in local kubevirt testing guide for provisioned cluster
  KUBEVIRTCI_LOCAL_TESTING.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#609 cnao, Bump cnao to v0.54.0
  cluster-provision/k8s/1.19/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.20/manifests/cnao/operator.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#591 Include vm-dump-metrics in the fedora-with-test-tooling image
  cluster-provision/images/vm-image-builder/fedora-with-test-tooling/cloud-config
Labels: approved, dco-signoff: yes, lgtm, size/XS

#611 Deploy rook ceph toolbox alongside ceph
  cluster-provision/k8s/1.17/manifests/ceph/toolbox.yaml
  cluster-provision/k8s/1.17/rook-ceph.sh
  cluster-provision/k8s/1.18/manifests/ceph/toolbox.yaml
  cluster-provision/k8s/1.18/rook-ceph.sh
  cluster-provision/k8s/1.19/manifests/ceph/toolbox.yaml
  cluster-provision/k8s/1.19/rook-ceph.sh
  cluster-provision/k8s/1.20/manifests/ceph/toolbox.yaml
  cluster-provision/k8s/1.20/rook-ceph.sh
  cluster-provision/k8s/1.21/manifests/ceph/toolbox.yaml
  cluster-provision/k8s/1.21/rook-ceph.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#606 Istio, Add configuration for cluster without CNAO
  cluster-provision/k8s/1.20/istio.sh
  cluster-provision/k8s/1.20/provision.sh
  cluster-provision/k8s/1.21/istio.sh
  cluster-provision/k8s/1.21/provision.sh
  cluster-up/cluster/k8s-provider-common.sh
Labels: approved, dco-signoff: yes, lgtm, size/M
