Repository kubevirt/kubevirtci, pull requests merged in 2021-04, with the labels that each got.

#583 Move slintes to emeritus
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#584 Remove NetworkManager version pinning on cluster provision
  cluster-provision/k8s/1.19/provision.sh
  cluster-provision/k8s/1.20/provision.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#576 docs, Update docs about testing locally provisioned clusters
  CONTRIBUTING.md
  KUBEVIRTCI_LOCAL_TESTING.md
  KUBEVIRT_LOCAL_TESTING.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#581 fix rook/ceph
  cluster-provision/gocli/cmd/run.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#578 docs, Update dev-guide with fresh k8s-1.17 deploy
  cluster-up/cluster/k8s-1.17/dev-guide.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#570 Add support for SRIOV Live Migration on SRIOV provider
  cluster-up/cluster/kind-k8s-sriov-1.17.0/README.md
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov_cluster.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/provider.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/sriov-node/configure_vfs.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/sriov-node/node.sh
  cluster-up/cluster/kind/manifests/product-uuid-podpreset.yaml
  cluster-up/cluster/kind/podpreset.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#533 Disable qemu guest agent at startup for fedora tools image
  cluster-provision/images/vm-image-builder/fedora-with-test-tooling/cloud-config
  cluster-provision/images/vm-image-builder/fedora-with-test-tooling/image-url
Labels: approved, dco-signoff: yes, lgtm, size/XS

#590 Configure Istio deployment to use multus cni
  cluster-provision/k8s/1.20/istio.sh
  cluster-provision/k8s/1.20/version
  cluster-provision/k8s/check-cluster-up.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#596 Enable invtsc
  cluster-provision/centos8/scripts/vm.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#598 Update k8s 1.20 sonobuoy configuration
  cluster-provision/k8s/1.20/conformance.json
Labels: approved, dco-signoff: yes, lgtm, size/M

#597 Create k8s-1.21 provider
  cluster-provision/k8s/1.21/base
  cluster-provision/k8s/1.21/bind_device_to_vfio.sh
  cluster-provision/k8s/1.21/conformance.json
  cluster-provision/k8s/1.21/istio.sh
  cluster-provision/k8s/1.21/logging.sh
  cluster-provision/k8s/1.21/manifests/ceph/cluster-test.yaml
  cluster-provision/k8s/1.21/manifests/ceph/common.yaml
  cluster-provision/k8s/1.21/manifests/ceph/crds.yaml
  cluster-provision/k8s/1.21/manifests/ceph/operator.yaml
  cluster-provision/k8s/1.21/manifests/ceph/pool-test.yaml
  cluster-provision/k8s/1.21/manifests/ceph/rbac-snapshot-controller.yaml
  cluster-provision/k8s/1.21/manifests/ceph/setup-snapshot-controller.yaml
  cluster-provision/k8s/1.21/manifests/ceph/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  cluster-provision/k8s/1.21/manifests/ceph/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  cluster-provision/k8s/1.21/manifests/ceph/snapshot.storage.k8s.io_volumesnapshots.yaml
  cluster-provision/k8s/1.21/manifests/ceph/snapshotclass.yaml
  cluster-provision/k8s/1.21/manifests/ceph/storageclass-test.yaml
  cluster-provision/k8s/1.21/manifests/cnao/namespace.yaml
  cluster-provision/k8s/1.21/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.21/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.21/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.21/manifests/cni.diff
  cluster-provision/k8s/1.21/manifests/cni.do-not-change.yaml
  cluster-provision/k8s/1.21/manifests/kubeadm.conf
  cluster-provision/k8s/1.21/manifests/local-volume.yaml
  cluster-provision/k8s/1.21/manifests/logging.yaml
  cluster-provision/k8s/1.21/node01.sh
  cluster-provision/k8s/1.21/nodes.sh
  cluster-provision/k8s/1.21/provision.sh
  cluster-provision/k8s/1.21/rook-ceph.sh
  cluster-provision/k8s/1.21/version
  cluster-up/cluster/k8s-1.21/README.md
  cluster-up/cluster/k8s-1.21/dev-guide.md
  cluster-up/cluster/k8s-1.21/provider.sh
  hack/conformance.sh
Labels: approved, dco-signoff: yes, lgtm, size/XXL
