Repository kubevirt/kubevirtci, pull requests merged in 2021-03, with the labels that each got.

#555 Bump calico to v3.18.0
  cluster-provision/k8s/1.17/manifests/cni.diff
  cluster-provision/k8s/1.17/manifests/cni.do-not-change.yaml
  cluster-provision/k8s/1.18/manifests/cni.diff
  cluster-provision/k8s/1.18/manifests/cni.do-not-change.yaml
  cluster-provision/k8s/1.19/manifests/cni.diff
  cluster-provision/k8s/1.19/manifests/cni.do-not-change.yaml
  cluster-provision/k8s/1.20/manifests/cni.diff
  cluster-provision/k8s/1.20/manifests/cni.do-not-change.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#558 Activate dual stack again
  cluster-provision/k8s/1.18/manifests/cni.diff
  cluster-provision/k8s/1.19/manifests/cni.diff
  cluster-provision/k8s/1.20/manifests/cni.diff
Labels: approved, dco-signoff: yes, lgtm, size/L

#561 Use calico 3.17 for k8s-1.17
  cluster-provision/k8s/1.17/manifests/cni.diff
  cluster-provision/k8s/1.17/manifests/cni.do-not-change.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#536 Add option to deploy istio service mesh
  cluster-provision/gocli/cmd/run.go
  cluster-provision/k8s/1.20/istio.sh
  cluster-provision/k8s/1.20/nodes.sh
  cluster-provision/k8s/1.20/provision.sh
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/hack/common.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#565 Use default values for node cidr mask size
  cluster-provision/centos8/version
  cluster-provision/k8s/1.18/manifests/cni.diff
  cluster-provision/k8s/1.18/manifests/kubeadm.conf
  cluster-provision/k8s/1.19/manifests/cni.diff
  cluster-provision/k8s/1.19/manifests/kubeadm.conf
  cluster-provision/k8s/1.20/manifests/cni.diff
  cluster-provision/k8s/1.20/manifests/kubeadm.conf
Labels: approved, dco-signoff: yes, lgtm, size/L

#557 Add Kubevirt conformance tests to check-provision jobs
  cluster-provision/k8s/1.17/conformance.json
  cluster-provision/k8s/1.18/conformance.json
  cluster-provision/k8s/1.19/conformance.json
  cluster-provision/k8s/1.20/conformance.json
  cluster-provision/k8s/check-cluster-up.sh
  hack/conformance.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#556 sriov vm image, Remove cloud-init user update module
  cluster-provision/images/vm-image-builder/fedora-sriov-lane/cloud-config
Labels: approved, dco-signoff: yes, lgtm, size/XS

#574 fix ceph selinux permissions
  cluster-provision/k8s/1.17/nodes.sh
  cluster-provision/k8s/1.17/rook-ceph.sh
  cluster-provision/k8s/1.18/nodes.sh
  cluster-provision/k8s/1.18/rook-ceph.sh
  cluster-provision/k8s/1.19/nodes.sh
  cluster-provision/k8s/1.19/rook-ceph.sh
  cluster-provision/k8s/1.20/nodes.sh
  cluster-provision/k8s/1.20/rook-ceph.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#551 sriov, Support running multi clusters side by side (locally)
  cluster-up/cluster/kind-k8s-sriov-1.17.0/README.md
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/provider.sh
  cluster-up/cluster/kind/common.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#577 fix single node rook/ceph
  cluster-provision/k8s/1.17/node01.sh
  cluster-provision/k8s/1.18/node01.sh
  cluster-provision/k8s/1.19/node01.sh
  cluster-provision/k8s/1.20/node01.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#553 fix make cluster-up error when using kind-k8s-1.17
  cluster-up/cluster/kind-k8s-1.17/README.md
  cluster-up/cluster/kind-k8s-1.17/provider.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#567 Configure cgroupv2 in k8s 1.20
  cluster-provision/gocli/cmd/provision.go
  cluster-provision/k8s/1.20/provision.sh
  cluster-provision/k8s/check-cluster-up.sh
  cluster-provision/k8s/provision.sh
  cluster-up/cluster/k8s-1.20-cgroupsv2/README.md
  cluster-up/cluster/k8s-1.20-cgroupsv2/provider.sh
  publish.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#563 SRIOV Provider use bare sriov components instead of sriov-network-operator
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/configure_vfs.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/sriov-components/manifests/kustomization.yaml
  cluster-up/cluster/kind-k8s-sriov-1.17.0/sriov-components/manifests/multus.yaml
  cluster-up/cluster/kind-k8s-sriov-1.17.0/sriov-components/manifests/patch-node-selector.yaml.in
  cluster-up/cluster/kind-k8s-sriov-1.17.0/sriov-components/manifests/patch-sriovdp-resource-prefix.yaml.in
  cluster-up/cluster/kind-k8s-sriov-1.17.0/sriov-components/manifests/sriov-cni-daemonset.yaml
  cluster-up/cluster/kind-k8s-sriov-1.17.0/sriov-components/manifests/sriov-ns.yaml
  cluster-up/cluster/kind-k8s-sriov-1.17.0/sriov-components/manifests/sriovdp-config.yaml.in
  cluster-up/cluster/kind-k8s-sriov-1.17.0/sriov-components/manifests/sriovdp-daemonset.yaml
  cluster-up/cluster/kind-k8s-sriov-1.17.0/sriov-components/sriov_components.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/sriov_operator.sh
Labels: approved, dco-signoff: yes, lgtm, size/XXL
