Repository kubevirt/kubevirtci, pull requests merged in 2021-12, with the labels that each got.

#696 Add bump-cdi shell script
  hack/bump-cdi.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#715 SR-IOV cluster config: Print /dev/vfio mode
  cluster-up/cluster/kind-1.19-sriov/sriov-node/node.sh
  cluster-up/cluster/kind-1.22-sriov/sriov-node/node.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#723 CI-cluster swap support
  cluster-provision/k8s/1.22/node01.sh
  cluster-provision/k8s/1.22/nodes.sh
  cluster-provision/k8s/1.22/provision.sh
  cluster-up/cluster/k8s-provider-common.sh
  cluster-up/hack/common.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#716 KinD providers: Mount the host audit logs dir to cluster nodes
  cluster-up/cluster/kind/common.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#724 KinD providers: Mount audit logs as read-only
  cluster-up/cluster/kind/common.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#725 Configure the nodes and kubeadm to avoid failure when swap is enabled with version 1.23
  cluster-provision/k8s/1.23/node01.sh
  cluster-provision/k8s/1.23/nodes.sh
  cluster-provision/k8s/1.23/provision.sh
Labels: size/S, approved, lgtm, dco-signoff: yes
