Repository kubevirt/kubevirtci, pull requests merged in 2021-08, with the labels that each got.

#647 Kind single node cluster to support testing mediated devices / vGPU
  cluster-up/cluster/kind-1.19-vgpu/README.md
  cluster-up/cluster/kind-1.19-vgpu/config_vgpu_cluster.sh
  cluster-up/cluster/kind-1.19-vgpu/provider.sh
  cluster-up/cluster/kind-1.19-vgpu/vgpu-node/node.sh
  cluster-up/cluster/kind/common.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#653 Expose CDI upload proxy port in CI clusters
  cluster-provision/centos8/scripts/vm.sh
  cluster-provision/gocli/cmd/ports.go
  cluster-provision/gocli/cmd/utils/ports.go
  cluster-provision/gocli/containers/dnsmasq.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#654 Forward ports from container to VM
  cluster-provision/centos8/scripts/vm.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#648 Consolidate test test tool images into a single one
  .gitignore
  cluster-provision/images/vm-image-builder/fedora-sriov-lane/cloud-config
  cluster-provision/images/vm-image-builder/fedora-sriov-lane/image-url
  cluster-provision/images/vm-image-builder/fedora-sriov-lane/os-variant
  cluster-provision/images/vm-image-builder/fedora-with-test-tooling/cloud-config
Labels: size/M, approved, lgtm, dco-signoff: yes

#656 Correct error caused by #654
  cluster-provision/centos8/scripts/vm.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#644 SRIOV provider: Deploy default CNI
  cluster-up/cluster/kind/common.sh
  cluster-up/cluster/kind/manifests/kind.yaml
  cluster-up/cluster/kind/manifests/kube-calico.diff.in
  cluster-up/cluster/kind/manifests/kube-calico.yaml.in
Labels: size/XL, approved, lgtm, dco-signoff: yes

#659 cdi, Bump cdi to 1.36.0 on k8s-1.21
  cluster-provision/k8s/1.21/manifests/cdi-1.36.0.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#661 Bump k8s providers
  cluster-provision/k8s/1.19/version
  cluster-provision/k8s/1.20/version
  cluster-provision/k8s/1.21/version
Labels: size/XS, approved, lgtm, dco-signoff: yes

#660 cluster-provision, Prefetch cdi images
  cluster-provision/k8s/1.19/manifests/cdi.do-not-change.yaml
  cluster-provision/k8s/1.19/provision.sh
  cluster-provision/k8s/1.20/manifests/cdi.do-not-change.yaml
  cluster-provision/k8s/1.20/provision.sh
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#664 cnao, Bump CNAO to 0.58.0
  cluster-provision/k8s/1.19/manifests/cnao/namespace.yaml
  cluster-provision/k8s/1.19/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.20/manifests/cnao/namespace.yaml
  cluster-provision/k8s/1.20/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.21/manifests/cnao/namespace.yaml
  cluster-provision/k8s/1.21/manifests/cnao/operator.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#666 sig-storage flake fix: report that our storage is fast
  cluster-provision/k8s/1.19/provision.sh
  cluster-provision/k8s/1.20/provision.sh
  cluster-provision/k8s/1.21/provision.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#669 Kind infra, Increase PodPreset enabled validation timeout
  cluster-up/cluster/kind/podpreset.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#612 Fix error redirection to stderr on kind/podpreset.sh
  cluster-up/cluster/kind/podpreset.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes
