Repository kubevirt/kubevirtci, pull requests merged in 2022-02, with the labels that each got.

#742 provision: Install ovs
  cluster-provision/k8s/1.20/provision.sh
  cluster-provision/k8s/1.21/provision.sh
  cluster-provision/k8s/1.22-ipv6/provision.sh
  cluster-provision/k8s/1.22/provision.sh
  cluster-provision/k8s/1.23/provision.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#745 Update default provider to k8s-1.21
  cluster-up/hack/common.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#746 Add kind-1.23-vgpu provider
  cluster-up/cluster/kind-1.23-vgpu/README.md
  cluster-up/cluster/kind-1.23-vgpu/config_vgpu_cluster.sh
  cluster-up/cluster/kind-1.23-vgpu/provider.sh
  cluster-up/cluster/kind-1.23-vgpu/vgpu-node/node.sh
Labels: size/L, approved, lgtm, dco-signoff: yes

#740 Bump cri-o versions
  cluster-provision/k8s/1.21/provision.sh
  cluster-provision/k8s/1.22-ipv6/provision.sh
  cluster-provision/k8s/1.22/provision.sh
  cluster-provision/k8s/1.23/provision.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#743 cluster-up: Avoid a known comon issue when using podman
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/k8s-provider-common.sh
Labels: size/S, ok-to-test, approved, lgtm, dco-signoff: yes

#749 Use skopeo to push image as workaround for "unknown blob"
  publish.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#741 cluster-up: Use podman.socket's default path
  PODMAN.md
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: size/S, ok-to-test, approved, lgtm, dco-signoff: yes
