Repository kubevirt/kubevirtci, pull requests merged in 2022-04, with the labels that each got.

#778 podman, docs: clarify rootless podman does not work w/ cluster-sync
  PODMAN.md
Labels: size/S, approved, lgtm, dco-signoff: yes

#775 Remove not supported kind 1.19
  cluster-up/cluster/kind-1.19-sriov/OWNERS
  cluster-up/cluster/kind-1.19-sriov/README.md
  cluster-up/cluster/kind-1.19-sriov/TROUBLESHOOTING.md
  cluster-up/cluster/kind-1.19-sriov/certcreator/certlib/selfsign.go
  cluster-up/cluster/kind-1.19-sriov/certcreator/certsecret.go
  cluster-up/cluster/kind-1.19-sriov/certcreator/go.mod
  cluster-up/cluster/kind-1.19-sriov/certcreator/go.sum
  cluster-up/cluster/kind-1.19-sriov/config_sriov_cluster.sh
  cluster-up/cluster/kind-1.19-sriov/conformance.json
  cluster-up/cluster/kind-1.19-sriov/manifests/network_config_policy.yaml
  cluster-up/cluster/kind-1.19-sriov/provider.sh
  cluster-up/cluster/kind-1.19-sriov/sriov-components/manifests/kustomization.yaml
  cluster-up/cluster/kind-1.19-sriov/sriov-components/manifests/multus.yaml
  cluster-up/cluster/kind-1.19-sriov/sriov-components/manifests/patch-node-selector.yaml.in
  cluster-up/cluster/kind-1.19-sriov/sriov-components/manifests/patch-sriovdp-resource-prefix.yaml.in
  cluster-up/cluster/kind-1.19-sriov/sriov-components/manifests/sriov-cni-daemonset.yaml
  cluster-up/cluster/kind-1.19-sriov/sriov-components/manifests/sriov-ns.yaml
  cluster-up/cluster/kind-1.19-sriov/sriov-components/manifests/sriovdp-config.yaml.in
  cluster-up/cluster/kind-1.19-sriov/sriov-components/manifests/sriovdp-daemonset.yaml
  cluster-up/cluster/kind-1.19-sriov/sriov-components/sriov_components.sh
  cluster-up/cluster/kind-1.19-sriov/sriov-node/configure_vfs.sh
  cluster-up/cluster/kind-1.19-sriov/sriov-node/node.sh
  cluster-up/cluster/kind-1.19-sriov/sriov_operator.sh
  cluster-up/cluster/kind-1.19-sriov/sriovdp_setup.sh
  cluster-up/cluster/kind-1.19-vgpu/README.md
  cluster-up/cluster/kind-1.19-vgpu/config_vgpu_cluster.sh
  cluster-up/cluster/kind-1.19-vgpu/provider.sh
  cluster-up/cluster/kind-1.19-vgpu/vgpu-node/node.sh
  cluster-up/cluster/kind-k8s-1.19/README.md
  cluster-up/cluster/kind-k8s-1.19/provider.sh
  cluster-up/cluster/kind/manifests/product-uuid-podpreset.yaml
  cluster-up/cluster/kind/podpreset.sh
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#777 Configure KinD clusters to use CI registry proxy (vGPU lane)
  cluster-up/cluster/kind-1.23-vgpu/provider.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#776 alpine: Reduce size and startup time
  cluster-provision/images/vm-image-builder/alpine-cloud-init/configure.sh
  cluster-provision/images/vm-image-builder/alpine-cloud-init/create-image.sh
  cluster-provision/images/vm-image-builder/alpine-cloud-init/packages
Labels: size/S, approved, lgtm, dco-signoff: yes

#781 alpine: Publish image on merge
  publish.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#782 Revert "kind: Use quay registry image"
  cluster-up/cluster/kind/common.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#783 k8s: Patch CNI before fetching
  cluster-provision/k8s/1.21/k8s_provision.sh
  cluster-provision/k8s/1.21/provision.sh
  cluster-provision/k8s/1.22-ipv6/k8s_provision.sh
  cluster-provision/k8s/1.22-ipv6/provision.sh
  cluster-provision/k8s/1.22/k8s_provision.sh
  cluster-provision/k8s/1.22/provision.sh
  cluster-provision/k8s/1.23/k8s_provision.sh
  cluster-provision/k8s/1.23/provision.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#780 alpine: Add guest agent to the image
  cluster-provision/images/vm-image-builder/alpine-cloud-init/configure.sh
  cluster-provision/images/vm-image-builder/alpine-cloud-init/packages
  cluster-provision/images/vm-image-builder/create-containerdisk.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#785 Ask to add awels as approver
  OWNERS
Labels: size/XS, approved, lgtm, dco-signoff: yes

#779 Bump kube-state-metrics to enable usage of some advanced metrics
  cluster-provision/k8s/1.21/manifests/prometheus/kube-state-metrics/kube-state-metrics-clusterRole.yaml
  cluster-provision/k8s/1.21/manifests/prometheus/kube-state-metrics/kube-state-metrics-clusterRoleBinding.yaml
  cluster-provision/k8s/1.21/manifests/prometheus/kube-state-metrics/kube-state-metrics-deployment.yaml
  cluster-provision/k8s/1.21/manifests/prometheus/kube-state-metrics/kube-state-metrics-prometheusRule.yaml
  cluster-provision/k8s/1.21/manifests/prometheus/kube-state-metrics/kube-state-metrics-service.yaml
  cluster-provision/k8s/1.21/manifests/prometheus/kube-state-metrics/kube-state-metrics-serviceAccount.yaml
  cluster-provision/k8s/1.21/manifests/prometheus/kube-state-metrics/kube-state-metrics-serviceMonitor.yaml
  cluster-provision/k8s/1.22-ipv6/manifests/prometheus/kube-state-metrics/kube-state-metrics-clusterRole.yaml
  cluster-provision/k8s/1.22-ipv6/manifests/prometheus/kube-state-metrics/kube-state-metrics-clusterRoleBinding.yaml
  cluster-provision/k8s/1.22-ipv6/manifests/prometheus/kube-state-metrics/kube-state-metrics-deployment.yaml
  cluster-provision/k8s/1.22-ipv6/manifests/prometheus/kube-state-metrics/kube-state-metrics-prometheusRule.yaml
  cluster-provision/k8s/1.22-ipv6/manifests/prometheus/kube-state-metrics/kube-state-metrics-service.yaml
  cluster-provision/k8s/1.22-ipv6/manifests/prometheus/kube-state-metrics/kube-state-metrics-serviceAccount.yaml
  cluster-provision/k8s/1.22-ipv6/manifests/prometheus/kube-state-metrics/kube-state-metrics-serviceMonitor.yaml
  cluster-provision/k8s/1.22/manifests/prometheus/kube-state-metrics/kube-state-metrics-clusterRole.yaml
  cluster-provision/k8s/1.22/manifests/prometheus/kube-state-metrics/kube-state-metrics-clusterRoleBinding.yaml
  cluster-provision/k8s/1.22/manifests/prometheus/kube-state-metrics/kube-state-metrics-deployment.yaml
  cluster-provision/k8s/1.22/manifests/prometheus/kube-state-metrics/kube-state-metrics-prometheusRule.yaml
  cluster-provision/k8s/1.22/manifests/prometheus/kube-state-metrics/kube-state-metrics-service.yaml
  cluster-provision/k8s/1.22/manifests/prometheus/kube-state-metrics/kube-state-metrics-serviceAccount.yaml
  cluster-provision/k8s/1.22/manifests/prometheus/kube-state-metrics/kube-state-metrics-serviceMonitor.yaml
  cluster-provision/k8s/1.23/manifests/prometheus/kube-state-metrics/kube-state-metrics-clusterRole.yaml
  cluster-provision/k8s/1.23/manifests/prometheus/kube-state-metrics/kube-state-metrics-clusterRoleBinding.yaml
  cluster-provision/k8s/1.23/manifests/prometheus/kube-state-metrics/kube-state-metrics-deployment.yaml
  cluster-provision/k8s/1.23/manifests/prometheus/kube-state-metrics/kube-state-metrics-prometheusRule.yaml
  cluster-provision/k8s/1.23/manifests/prometheus/kube-state-metrics/kube-state-metrics-service.yaml
  cluster-provision/k8s/1.23/manifests/prometheus/kube-state-metrics/kube-state-metrics-serviceAccount.yaml
  cluster-provision/k8s/1.23/manifests/prometheus/kube-state-metrics/kube-state-metrics-serviceMonitor.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#773 Avoid `make cluster-down` failures
  cluster-up/cluster/kind/common.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes
