Repository kubevirt/kubevirtci, pull requests merged in 2022-05, with the labels that each got.

#795 push alpine-cloud-init to quay.io/kubevirt/
  publish.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#790 Add missing conformance test configuration
  cluster-up/cluster/kind-1.23-vgpu/conformance.json
Labels: size/M, approved, lgtm, dco-signoff: yes

#789 kind: Use quay registry image
  cluster-up/cluster/kind/common.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#798 alpine: Use vport2p1 ga path
  cluster-provision/images/vm-image-builder/alpine-cloud-init/configure.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#803 Bump rook-ceph 1.7.1 -> 1.8.9
  cluster-provision/k8s/1.21/manifests/ceph/cluster-test.yaml
  cluster-provision/k8s/1.21/manifests/ceph/common.yaml
  cluster-provision/k8s/1.21/manifests/ceph/crds.yaml
  cluster-provision/k8s/1.21/manifests/ceph/operator.yaml
  cluster-provision/k8s/1.21/manifests/ceph/toolbox.yaml
  cluster-provision/k8s/1.22-ipv6/manifests/ceph/cluster-test.yaml
  cluster-provision/k8s/1.22-ipv6/manifests/ceph/common.yaml
  cluster-provision/k8s/1.22-ipv6/manifests/ceph/crds.yaml
  cluster-provision/k8s/1.22-ipv6/manifests/ceph/operator.yaml
  cluster-provision/k8s/1.22-ipv6/manifests/ceph/toolbox.yaml
  cluster-provision/k8s/1.22/manifests/ceph/cluster-test.yaml
  cluster-provision/k8s/1.22/manifests/ceph/common.yaml
  cluster-provision/k8s/1.22/manifests/ceph/crds.yaml
  cluster-provision/k8s/1.22/manifests/ceph/operator.yaml
  cluster-provision/k8s/1.22/manifests/ceph/toolbox.yaml
  cluster-provision/k8s/1.23/manifests/ceph/cluster-test.yaml
  cluster-provision/k8s/1.23/manifests/ceph/common.yaml
  cluster-provision/k8s/1.23/manifests/ceph/crds.yaml
  cluster-provision/k8s/1.23/manifests/ceph/operator.yaml
  cluster-provision/k8s/1.23/manifests/ceph/toolbox.yaml
Labels: size/XXL, approved, lgtm, dco-signoff: yes
