Repository kubevirt/kubevirtci, pull requests merged in 2022-08, with the labels that each got.

#849 Switch to a fork of the Fedora image to get a stable hash
  cluster-provision/centos8/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#851 istio: Use quay.io as the hub
  cluster-provision/k8s/1.22/extra-pre-pull-images
  cluster-provision/k8s/1.22/istio.sh
  cluster-provision/k8s/1.22/provision.sh
  cluster-provision/k8s/1.23/extra-pre-pull-images
  cluster-provision/k8s/1.23/istio.sh
  cluster-provision/k8s/1.23/provision.sh
  cluster-provision/k8s/1.24-ipv6/extra-pre-pull-images
  cluster-provision/k8s/1.24-ipv6/istio.sh
  cluster-provision/k8s/1.24-ipv6/provision.sh
  cluster-provision/k8s/1.24/extra-pre-pull-images
  cluster-provision/k8s/1.24/istio.sh
  cluster-provision/k8s/1.24/provision.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#821 Bump SR-IOV proivider components
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/kustomization.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/multus/kustomization.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/multus/multus.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/sriov-cni-daemonset.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/sriovdp-daemonset.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#847 whereabouts: bump to v0.5.4
  cluster-provision/k8s/1.22/manifests/whereabouts/whereabouts-v0.5.4.yaml
  cluster-provision/k8s/1.23/manifests/whereabouts/whereabouts-v0.5.4.yaml
  cluster-provision/k8s/1.24-ipv6/manifests/whereabouts/whereabouts-v0.5.4.yaml
  cluster-provision/k8s/1.24/manifests/whereabouts/whereabouts-v0.5.4.yaml
  hack/bump-whereabouts.sh
  hack/kustomization/whereabouts/kustomization.yaml
  hack/kustomization/whereabouts/patch-ip-reconciler-job.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#854 Nominate brianmcarey to be approver
  OWNERS
Labels: size/XS, approved, lgtm, dco-signoff: yes

#859 Don't wait for ceph toolbox to be deployed: we no longer deploy it
  cluster-provision/k8s/1.22/rook-ceph.sh
  cluster-provision/k8s/1.23/rook-ceph.sh
  cluster-provision/k8s/1.24-ipv6/rook-ceph.sh
  cluster-provision/k8s/1.24/rook-ceph.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#863 Revert "vm based providers: Introduce KUBEVIRT_DEPLOY_LOCAL_STORAGE"
  cluster-provision/k8s/1.22/node01.sh
  cluster-provision/k8s/1.23/node01.sh
  cluster-provision/k8s/1.24-ipv6/node01.sh
  cluster-provision/k8s/1.24/node01.sh
  cluster-up/cluster/k8s-provider-common.sh
  cluster-up/hack/common.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#853 grafana: Use quay mirror
  cluster-provision/gocli/cmd/provision.go
  cluster-provision/k8s/1.22/extra-pre-pull-images
  cluster-provision/k8s/1.22/manifests/prometheus/grafana/kustomization.yaml
  cluster-provision/k8s/1.22/provision.sh
  cluster-provision/k8s/1.23/extra-pre-pull-images
  cluster-provision/k8s/1.23/manifests/prometheus/grafana/kustomization.yaml
  cluster-provision/k8s/1.23/provision.sh
  cluster-provision/k8s/1.24-ipv6/extra-pre-pull-images
  cluster-provision/k8s/1.24-ipv6/manifests/prometheus/grafana/kustomization.yaml
  cluster-provision/k8s/1.24-ipv6/provision.sh
  cluster-provision/k8s/1.24/extra-pre-pull-images
  cluster-provision/k8s/1.24/manifests/prometheus/grafana/kustomization.yaml
  cluster-provision/k8s/1.24/provision.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#861 Revert "vm based providers: Pin NetworkManager version (#841)"
  cluster-provision/k8s/1.22/k8s_provision.sh
  cluster-provision/k8s/1.23/k8s_provision.sh
  cluster-provision/k8s/1.24-ipv6/k8s_provision.sh
  cluster-provision/k8s/1.24/k8s_provision.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#864 Upgrade cri-o to version 1.24 for 1.24 providers
  cluster-provision/k8s/1.24-ipv6/provision.sh
  cluster-provision/k8s/1.24/provision.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#848 registry proxy: Fix crio support
  K8S.md
  cluster-provision/gocli/cmd/run.go
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: size/S, approved, lgtm, dco-signoff: yes
