Repository kubevirt/kubevirtci, pull requests merged in 2022-06, with the labels that each got.

#805 cnao: Bump to version v0.76.0
  cluster-provision/k8s/1.21/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.21/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.21/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.22-ipv6/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.22-ipv6/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.22-ipv6/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.22/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.22/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.22/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.23/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.23/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.23/manifests/cnao/operator.yaml
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#809 Downgrade cri-o to 1.22 due to intermittent issue with cri-o 1.24
  cluster-provision/k8s/1.24/provision.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#812 SR-IOV Provider: Patch Multus manifest using Kustomize
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/multus/kustomization.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/multus/multus.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/sriov_components.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#811 SR-IOV Provider: Raise Multus Log Verbosity
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/multus/kustomization.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/multus/patch-args.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#815 alpine image: Install iputils
  cluster-provision/images/vm-image-builder/alpine-cloud-init/packages
Labels: size/XS, approved, lgtm, dco-signoff: yes

#816 dnsmasq: Don't use ipv6 local address a dns server
  cluster-provision/centos8/scripts/dnsmasq.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#810 alpine: Bump alpine image to 3.16
  cluster-provision/images/vm-image-builder/alpine-cloud-init/configure.sh
  cluster-provision/images/vm-image-builder/alpine-cloud-init/create-image.sh
  cluster-provision/images/vm-image-builder/alpine-cloud-init/packages
Labels: size/S, approved, lgtm, dco-signoff: yes

#819 alpine: Revert boot timeout removal
  cluster-provision/images/vm-image-builder/alpine-cloud-init/configure.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#820 sriov provider, multus: Raise log verbosity level
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/multus/patch-args.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#822 Alpine extended image: add curl
  cluster-provision/images/vm-image-builder/alpine-cloud-init/packages
Labels: size/XS, approved, lgtm, dco-signoff: yes

#823 Sync ceph bumps to 1.24 as well
  cluster-provision/k8s/1.24-ipv6/manifests/ceph/cluster-test.yaml
  cluster-provision/k8s/1.24-ipv6/manifests/ceph/common.yaml
  cluster-provision/k8s/1.24-ipv6/manifests/ceph/crds.yaml
  cluster-provision/k8s/1.24-ipv6/manifests/ceph/operator.yaml
  cluster-provision/k8s/1.24-ipv6/manifests/ceph/toolbox.yaml
  cluster-provision/k8s/1.24/manifests/ceph/cluster-test.yaml
  cluster-provision/k8s/1.24/manifests/ceph/common.yaml
  cluster-provision/k8s/1.24/manifests/ceph/crds.yaml
  cluster-provision/k8s/1.24/manifests/ceph/operator.yaml
  cluster-provision/k8s/1.24/manifests/ceph/toolbox.yaml
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#825 alpine: Run sshd at startup
  cluster-provision/images/vm-image-builder/alpine-cloud-init/configure.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#799 Update cluster provisioning image to fedora 36
  cluster-provision/centos8/Dockerfile
  cluster-provision/centos8/scripts/vm.sh
  cluster-provision/gocli/cmd/provision.go
Labels: size/S, approved, lgtm, dco-signoff: yes
