Repository kubevirt/kubevirtci, pull requests merged in 2022-12, with the labels that each got.

#913 SR-IOV providers: Bump SR-IOV CNI to v2.7.0
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/sriov-cni-daemonset.yaml
  cluster-up/cluster/kind-1.23-sriov/sriov-components/manifests/sriov-cni-daemonset.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#920 Revert "bump, cnao: k8s-1.2[4,5] to cnao v0.82.0 (#910)"
  cluster-provision/k8s/1.24/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.24/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.24/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.25/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.25/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.25/manifests/cnao/operator.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#924 Update Centos Stream 9 version to a stable version
  cluster-provision/centos9/version
Labels: size/XS, approved, lgtm, dco-signoff: yes

#921 gocli: add an option to enable FIPS
  cluster-provision/gocli/cmd/run.go
Labels: size/M, approved, lgtm, dco-signoff: yes

#923 Remove kind-1.22-sriov provider as no longer needed
  cluster-up/cluster/kind-1.22-sriov/OWNERS
  cluster-up/cluster/kind-1.22-sriov/README.md
  cluster-up/cluster/kind-1.22-sriov/TROUBLESHOOTING.md
  cluster-up/cluster/kind-1.22-sriov/certcreator/certlib/selfsign.go
  cluster-up/cluster/kind-1.22-sriov/certcreator/certsecret.go
  cluster-up/cluster/kind-1.22-sriov/certcreator/go.mod
  cluster-up/cluster/kind-1.22-sriov/certcreator/go.sum
  cluster-up/cluster/kind-1.22-sriov/config_sriov_cluster.sh
  cluster-up/cluster/kind-1.22-sriov/conformance.json
  cluster-up/cluster/kind-1.22-sriov/manifests/network_config_policy.yaml
  cluster-up/cluster/kind-1.22-sriov/provider.sh
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/kustomization.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/multus/kustomization.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/multus/multus.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/multus/patch-args.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/patch-node-selector.yaml.in
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/patch-sriovdp-resource-prefix.yaml.in
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/sriov-cni-daemonset.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/sriov-ns.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/sriovdp-config.yaml.in
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/sriovdp-daemonset.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/sriov_components.sh
  cluster-up/cluster/kind-1.22-sriov/sriov-node/configure_vfs.sh
  cluster-up/cluster/kind-1.22-sriov/sriov-node/node.sh
  cluster-up/cluster/kind-1.22-sriov/sriov_operator.sh
  cluster-up/cluster/kind-1.22-sriov/sriovdp_setup.sh
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#927 bump 1.26 to release
  cluster-provision/k8s/1.26/provision.sh
  cluster-provision/k8s/1.26/version
Labels: size/M, approved, lgtm, dco-signoff: yes

#930 Upgrade cri-o to version 1.25 for 1.25/6 providers
  cluster-provision/k8s/1.25-ipv6/provision.sh
  cluster-provision/k8s/1.25/provision.sh
  cluster-provision/k8s/1.26/provision.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#931 cluster-up: add environment variable to enable FIPS
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#932 k8s, cluster-up: Copy istio CNI net conf to where Multus expects
  cluster-up/cluster/k8s-provider-common.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#933 bump, cnao: k8s-1.2[4,5] to cnao v0.82.0 -- take2
  cluster-provision/k8s/1.24/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.24/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.24/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.25/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.25/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.25/manifests/cnao/operator.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#934 bump, cnao: k8s-1.26 to cnao v0.82.0
  cluster-provision/k8s/1.26/manifests/cnao/operator.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#935 psa: Fix bash error
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/hack/common.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes
