Repository kubevirt/kubevirtci, pull requests merged in 2022-07, with the labels that each got.

#826 kind providers: Support Podman auto detection
  cluster-up/cluster/kind-1.22-sriov/provider.sh
  cluster-up/cluster/kind-1.22-sriov/sriov-node/node.sh
  cluster-up/cluster/kind/common.sh
  cluster-up/cluster/kind/configure-registry-proxy.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#824 podman: Support non root user via root socket
  PODMAN.md
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/k8s-provider-common.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#829 Use full name for check-image-pull-policies image
  cluster-provision/k8s/validate-manifest-pull-policies.sh
  cluster-provision/k8s/validate-pod-pull-policies.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#830 publish: Fix script to support single stack providers
  publish.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#838 Update whereabouts image tag to match the manifest version
  cluster-provision/k8s/1.22-ipv6/manifests/whereabouts/whereabouts-v0.5.yaml
  cluster-provision/k8s/1.22/manifests/whereabouts/whereabouts-v0.5.yaml
  cluster-provision/k8s/1.23/manifests/whereabouts/whereabouts-v0.5.yaml
  cluster-provision/k8s/1.24-ipv6/manifests/whereabouts/whereabouts-v0.5.yaml
  cluster-provision/k8s/1.24/manifests/whereabouts/whereabouts-v0.5.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#828 Update the qemu sound devices to use the -device flag
  cluster-provision/centos8/scripts/vm.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#784 cluster-up, kind: add kind-1.23
  cluster-up/cluster/kind-1.23/README.md
  cluster-up/cluster/kind-1.23/provider.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#841 vm based providers: Pin NetworkManager version
  cluster-provision/k8s/1.22/k8s_provision.sh
  cluster-provision/k8s/1.23/k8s_provision.sh
  cluster-provision/k8s/1.24-ipv6/k8s_provision.sh
  cluster-provision/k8s/1.24/k8s_provision.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#842 add sg3 util
  cluster-provision/images/vm-image-builder/fedora-with-test-tooling/cloud-config
Labels: size/XS, approved, lgtm, dco-signoff: yes

#833 podman: Present socket env var
  PODMAN.md
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#844 vm based: Update readme about using console
  K8S.md
Labels: size/XS, approved, lgtm, dco-signoff: yes

#846 vm based: Add validation that single stack is indeed as expected
  cluster-provision/k8s/check-cluster-up.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#845 kind: Adapt check-cluster-up to auto detect CRI
  cluster-up/cluster/kind/check-cluster-up.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes
