Repository kubevirt/kubevirtci, pull requests merged in 2022-09, with the labels that each got.

#871 Fixed some typos in cluster-provision/README.md
  cluster-provision/README.md
Labels: size/XS, ok-to-test, approved, lgtm, dco-signoff: yes

#873 Pin containers-common to a specific version
  cluster-provision/k8s/1.22/provision.sh
  cluster-provision/k8s/1.23/provision.sh
  cluster-provision/k8s/1.24-ipv6/provision.sh
  cluster-provision/k8s/1.24/provision.sh
Labels: size/S, ok-to-test, approved, lgtm, dco-signoff: yes

#876 Fix cloud init on alpine with test tooling
  cluster-provision/images/vm-image-builder/alpine-cloud-init/configure.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#875 Retry removing containers that may have failed to delete due to dependent containers
  cluster-provision/gocli/docker/docker.go
Labels: size/XS, approved, lgtm, dco-signoff: yes

#879 Bump minor version of 1.24-ipv6 & 1.24-psa providers
  cluster-provision/k8s/1.24-ipv6/version
  cluster-provision/k8s/1.24-psa/version
Labels: size/XS, approved, lgtm, dco-signoff: yes

#884 Bump centos 8 version, add bump script
  cluster-provision/centos8/version
  hack/bump-centos-version.sh
Labels: size/S, approved, lgtm, dco-signoff: yes
