Repository kubevirt/kubevirtci, pull requests merged in 2022-10, with the labels that each got.

#857 Update sonobuoy version to v0.56.9
  cluster-provision/k8s/1.22/conformance.json
  cluster-provision/k8s/1.23/conformance.json
  cluster-provision/k8s/1.24-ipv6/conformance.json
  cluster-provision/k8s/1.24-psa/conformance.json
  cluster-provision/k8s/1.24/conformance.json
  cluster-up/cluster/kind-1.22-sriov/conformance.json
  cluster-up/cluster/kind-1.23-vgpu/conformance.json
  hack/conformance-image-config.yaml
  hack/conformance.sh
Labels: size/L, approved, lgtm, dco-signoff: yes

#890 bump: k8s-1.2[4,5] to cnao v0.80.0
  cluster-provision/k8s/1.24/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.25/manifests/cnao/operator.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#891 kind-1.22-sriov, provider.sh: Remove unused SRIOV_TESTS_NS variable
  cluster-up/cluster/kind-1.22-sriov/provider.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes
