Repository kubevirt/kubevirtci, pull requests merged in 2022-01, with the labels that each got.

#731 provision: Remove fluentd logging feature
  cluster-provision/gocli/cmd/run.go
  cluster-provision/gocli/cmd/utils/images.go
  cluster-provision/k8s/1.20/logging.sh
  cluster-provision/k8s/1.20/manifests/logging.yaml
  cluster-provision/k8s/1.20/provision.sh
  cluster-provision/k8s/1.21/extra-pre-pull-images
  cluster-provision/k8s/1.21/logging.sh
  cluster-provision/k8s/1.21/manifests/logging.yaml
  cluster-provision/k8s/1.22-ipv6/extra-pre-pull-images
  cluster-provision/k8s/1.22-ipv6/logging.sh
  cluster-provision/k8s/1.22-ipv6/manifests/logging.yaml
  cluster-provision/k8s/1.22/extra-pre-pull-images
  cluster-provision/k8s/1.22/logging.sh
  cluster-provision/k8s/1.22/manifests/logging.yaml
  cluster-provision/k8s/1.23/extra-pre-pull-images
  cluster-provision/k8s/1.23/logging.sh
  cluster-provision/k8s/1.23/manifests/logging.yaml
  cluster-provision/k8s/README.md
  cluster-provision/k8s/deploy-manifests.sh
  cluster-up/cluster/K8S_DEV_GUIDE.md
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#730 bump-cdi script: Update script to include also k8s-1.22-ipv6
  hack/bump-cdi.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#733 console: Use screen instead of socat
  K8S.md
  cluster-provision/centos8/Dockerfile
  cluster-provision/gocli/cmd/run.go
Labels: size/S, approved, lgtm, dco-signoff: yes

#734 Add second sound card
  cluster-provision/centos8/scripts/vm.sh
  cluster-provision/gocli/cmd/run.go
Labels: size/S, approved, lgtm, dco-signoff: yes

#735 vm based providers, prometheus: Fix copy paste typo
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#738 fedora-with-test-tooling: add tpm2-tools for vTPM functests
  cluster-provision/images/vm-image-builder/fedora-with-test-tooling/cloud-config
Labels: size/XS, approved, lgtm, dco-signoff: yes
