Repository kubevirt/kubevirtci, pull requests merged in 2022-11, with the labels that each got.

#867 vm based providers: Expose a UDP port for DNS
  cluster-provision/centos8/Dockerfile
  cluster-provision/centos8/scripts/vm.sh
  cluster-provision/gocli/cmd/ports.go
  cluster-provision/gocli/cmd/provision.go
  cluster-provision/gocli/cmd/run.go
  cluster-provision/gocli/cmd/utils/ports.go
  cluster-provision/gocli/cmd/utils/utils.go
  cluster-provision/gocli/containers/dnsmasq.go
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#894 Bump default provider version
  K8S.md
  KUBEVIRTCI_LOCAL_TESTING.md
  cluster-up/hack/common.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#895 bump: k8s-1.2[4,5] to cnao v0.81.0
  cluster-provision/k8s/1.24/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.24/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.24/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.25/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.25/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.25/manifests/cnao/operator.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#897 Create kind-1.23-sriov provider
  cluster-up/cluster/kind-1.23-sriov/OWNERS
  cluster-up/cluster/kind-1.23-sriov/README.md
  cluster-up/cluster/kind-1.23-sriov/TROUBLESHOOTING.md
  cluster-up/cluster/kind-1.23-sriov/certcreator/certlib/selfsign.go
  cluster-up/cluster/kind-1.23-sriov/certcreator/certsecret.go
  cluster-up/cluster/kind-1.23-sriov/certcreator/go.mod
  cluster-up/cluster/kind-1.23-sriov/certcreator/go.sum
  cluster-up/cluster/kind-1.23-sriov/config_sriov_cluster.sh
  cluster-up/cluster/kind-1.23-sriov/conformance.json
  cluster-up/cluster/kind-1.23-sriov/manifests/network_config_policy.yaml
  cluster-up/cluster/kind-1.23-sriov/provider.sh
  cluster-up/cluster/kind-1.23-sriov/sriov-components/manifests/kustomization.yaml
  cluster-up/cluster/kind-1.23-sriov/sriov-components/manifests/multus/kustomization.yaml
  cluster-up/cluster/kind-1.23-sriov/sriov-components/manifests/multus/multus.yaml
  cluster-up/cluster/kind-1.23-sriov/sriov-components/manifests/multus/patch-args.yaml
  cluster-up/cluster/kind-1.23-sriov/sriov-components/manifests/patch-node-selector.yaml.in
  cluster-up/cluster/kind-1.23-sriov/sriov-components/manifests/patch-sriovdp-resource-prefix.yaml.in
  cluster-up/cluster/kind-1.23-sriov/sriov-components/manifests/sriov-cni-daemonset.yaml
  cluster-up/cluster/kind-1.23-sriov/sriov-components/manifests/sriov-ns.yaml
  cluster-up/cluster/kind-1.23-sriov/sriov-components/manifests/sriovdp-config.yaml.in
  cluster-up/cluster/kind-1.23-sriov/sriov-components/manifests/sriovdp-daemonset.yaml
  cluster-up/cluster/kind-1.23-sriov/sriov-components/sriov_components.sh
  cluster-up/cluster/kind-1.23-sriov/sriov-node/configure_vfs.sh
  cluster-up/cluster/kind-1.23-sriov/sriov-node/node.sh
  cluster-up/cluster/kind-1.23-sriov/sriov_operator.sh
  cluster-up/cluster/kind-1.23-sriov/sriovdp_setup.sh
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#899 kind-1.23-sriov: Remove SR-IOV operator leftovers
  cluster-up/cluster/kind-1.23-sriov/certcreator/certlib/selfsign.go
  cluster-up/cluster/kind-1.23-sriov/certcreator/certsecret.go
  cluster-up/cluster/kind-1.23-sriov/certcreator/go.mod
  cluster-up/cluster/kind-1.23-sriov/certcreator/go.sum
  cluster-up/cluster/kind-1.23-sriov/manifests/network_config_policy.yaml
  cluster-up/cluster/kind-1.23-sriov/sriov_operator.sh
Labels: size/XL, approved, lgtm, dco-signoff: yes

#903 vm based providers: Change default dns host port
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#904 Revert "bump: k8s-1.2[4,5] to cnao v0.81.0 (#895)"
  cluster-provision/k8s/1.24/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.24/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.24/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.25/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.25/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.25/manifests/cnao/operator.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#909 Add centos9 image build to publish.sh
  publish.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#910 bump, cnao: k8s-1.2[4,5] to cnao v0.82.0
  cluster-provision/k8s/1.24/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.24/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.24/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.25/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.25/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.25/manifests/cnao/operator.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes
