Repository kubevirt/kubevirtci, pull requests merged in 2023-07, with the labels that each got.

#1038 provision: add debug option for virt-install
  cluster-provision/images/vm-image-builder/README.md
  cluster-provision/images/vm-image-builder/customize-image.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#1039 provision: print debug information when cleanup in vm-image-builder
  cluster-provision/images/vm-image-builder/customize-image.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1044 Manually bump CDI to v1.57.0-rc1
  cluster-provision/k8s/1.25/manifests/cdi-1.57.0-rc1-cr.yaml
  cluster-provision/k8s/1.25/manifests/cdi-1.57.0-rc1-operator.yaml
  cluster-provision/k8s/1.26-centos9/manifests/cdi-1.57.0-rc1-cr.yaml
  cluster-provision/k8s/1.26-centos9/manifests/cdi-1.57.0-rc1-operator.yaml
  cluster-provision/k8s/1.27/manifests/cdi-1.57.0-rc1-cr.yaml
  cluster-provision/k8s/1.27/manifests/cdi-1.57.0-rc1-operator.yaml
Labels: size/XL, approved, lgtm, dco-signoff: yes

#1040 kind-sriov: gracefully detach nics
  cluster-up/cluster/kind/common.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1042 vm based providers: Allow using custom images URL
  KUBEVIRTCI_LOCAL_TESTING.md
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#1047 cnao, provision: Bump vm based providers CNAO to v0.87.0
  cluster-provision/k8s/1.25/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.25/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.25/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.26-centos9/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.26-centos9/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.26-centos9/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.27/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.27/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.27/manifests/cnao/operator.yaml
Labels: size/XL, approved, lgtm, dco-signoff: yes

#1055 Fix regex in KUBEVIRT_CUSTOM_CDI_VERSION
  cluster-up/cluster/k8s-provider-common.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1054 vm based providers: Fix cluster-up script
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1052 Improve err msg on cluster image pull
  cluster-provision/gocli/cmd/run.go
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1043 kind, SR-IOV: Arrange to functions
  cluster-up/cluster/kind-1.27-sriov/provider.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#1058 Update github.com/opencontainers/runc to 1.1.5 in gocli
  cluster-provision/gocli/go.mod
  cluster-provision/gocli/go.sum
  cluster-provision/gocli/vendor/github.com/moby/sys/mountinfo/mounted_linux.go
  cluster-provision/gocli/vendor/github.com/moby/sys/mountinfo/mounted_unix.go
  cluster-provision/gocli/vendor/github.com/moby/sys/mountinfo/mountinfo.go
  cluster-provision/gocli/vendor/github.com/moby/sys/mountinfo/mountinfo_bsd.go
  cluster-provision/gocli/vendor/github.com/moby/sys/mountinfo/mountinfo_linux.go
  cluster-provision/gocli/vendor/github.com/moby/sys/mountinfo/mountinfo_unsupported.go
  cluster-provision/gocli/vendor/github.com/opencontainers/runc/libcontainer/user/lookup_unix.go
  cluster-provision/gocli/vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  cluster-provision/gocli/vendor/github.com/opencontainers/runc/libcontainer/user/user_fuzzer.go
  cluster-provision/gocli/vendor/modules.txt
Labels: size/L, approved, lgtm, dco-signoff: yes

#1061 Upgrade 1.28 provider to beta v1.28.0-beta.0
  cluster-provision/k8s/1.28/version
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1062 pman: Update rules.yaml with k8s-1.28
  hack/pman/rules.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1060 provision: add print_debug_log function in vm-image-builder
  cluster-provision/images/vm-image-builder/create-containerdisk.sh
  cluster-provision/images/vm-image-builder/customize-image.sh
  cluster-provision/images/vm-image-builder/example/image-url
  cluster-provision/images/vm-image-builder/fedora-realtime/image-url
  cluster-provision/images/vm-image-builder/fedora-with-test-tooling/image-url
Labels: size/S, approved, lgtm, dco-signoff: yes

#1063 Upgrade 1.28 provider to rc0 release
  cluster-provision/k8s/1.28/version
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1064 Add kubelet to the replaced binaries for kubernetes pre releases
  cluster-provision/k8s/1.28/provision.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#1065 Remove `--os-type` flag from customize-image.sh as it is deprecated
  cluster-provision/images/vm-image-builder/customize-image.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes
