Repository kubevirt/kubevirtci, pull requests merged in 2023-09, with the labels that each got.

#1077 Downgrade k8s-1.27 to 1.27.1
  cluster-provision/k8s/1.27/version
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1080 Remove the pinning of CentOS Stream kernel version
  cluster-provision/centos9/Dockerfile
  cluster-provision/centos9/version
Labels: size/S, approved, lgtm, dco-signoff: yes

#1082 cluster-up kind: enable the configuration of the ip family
  cluster-up/cluster/kind/common.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#1081 fedora-with-test-tooling: use bosybox version netcat
  cluster-provision/images/vm-image-builder/fedora-with-test-tooling/cloud-config
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1085 centos9: Bump version
  cluster-provision/centos9/version
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1084 centos9: Add missing UDP iptables rule
  cluster-provision/centos9/Dockerfile
  cluster-provision/centos9/scripts/vm.sh
Labels: size/M, approved, lgtm, dco-signoff: yes
