Repository kubevirt/kubevirtci, pull requests merged in 2023-12, with the labels that each got.

#1101 Bump provisioning base image to fedora 39
  cluster-provision/centos9/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1103 Install nftables on nodes as required by some network tests
  cluster-provision/k8s/1.26-centos9/provision.sh
  cluster-provision/k8s/1.27/provision.sh
  cluster-provision/k8s/1.28/provision.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#1102 Remove the local cluster provider as no longer used
  cluster-up/cluster/local/README.md
  cluster-up/cluster/local/provider.sh
  hack/pman/rules.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#1078 Align the cri-o version v1.28.0 with kubernetes version
  cluster-provision/k8s/1.28/provision.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#1105 Remove hardcoding of kubernetes repo version
  cluster-provision/k8s/1.28/provision.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1108 Bump NFS CSI to latest released version
  cluster-provision/k8s/1.26-centos9/manifests/nfs-csi/csi-nfs-controller-rbac.yaml
  cluster-provision/k8s/1.26-centos9/manifests/nfs-csi/csi-nfs-controller.yaml
  cluster-provision/k8s/1.26-centos9/manifests/nfs-csi/csi-nfs-driverinfo.yaml
  cluster-provision/k8s/1.26-centos9/manifests/nfs-csi/csi-nfs-node.yaml
  cluster-provision/k8s/1.26-centos9/manifests/nfs-csi/csi-nfs-sc.yaml
  cluster-provision/k8s/1.27/manifests/nfs-csi/csi-nfs-controller-rbac.yaml
  cluster-provision/k8s/1.27/manifests/nfs-csi/csi-nfs-controller.yaml
  cluster-provision/k8s/1.27/manifests/nfs-csi/csi-nfs-driverinfo.yaml
  cluster-provision/k8s/1.27/manifests/nfs-csi/csi-nfs-node.yaml
  cluster-provision/k8s/1.27/manifests/nfs-csi/csi-nfs-sc.yaml
  cluster-provision/k8s/1.28/manifests/nfs-csi/csi-nfs-controller-rbac.yaml
  cluster-provision/k8s/1.28/manifests/nfs-csi/csi-nfs-controller.yaml
  cluster-provision/k8s/1.28/manifests/nfs-csi/csi-nfs-driverinfo.yaml
  cluster-provision/k8s/1.28/manifests/nfs-csi/csi-nfs-node.yaml
  cluster-provision/k8s/1.28/manifests/nfs-csi/csi-nfs-sc.yaml
  cluster-provision/k8s/1.29/manifests/nfs-csi/csi-nfs-controller-rbac.yaml
  cluster-provision/k8s/1.29/manifests/nfs-csi/csi-nfs-controller.yaml
  cluster-provision/k8s/1.29/manifests/nfs-csi/csi-nfs-driverinfo.yaml
  cluster-provision/k8s/1.29/manifests/nfs-csi/csi-nfs-node.yaml
  cluster-provision/k8s/1.29/manifests/nfs-csi/csi-nfs-sc.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes
