Repository kubevirt/kubevirtci, pull requests merged in 2023-03, with the labels that each got.

#975 centos8: update SELinux policy version
  cluster-provision/k8s/1.24/provision.sh
  cluster-provision/k8s/1.25/provision.sh
  cluster-provision/k8s/1.26/provision.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#971 Fix some typos
  cluster-provision/README.md
  cluster-provision/images/README.md
  cluster-provision/k8s/1.26-centos9/manifests/prometheus/README.md
Labels: size/XS, ok-to-test, approved, lgtm, dco-signoff: yes

#979 kind, vgpu: Bump vgpu kind to k8s-1.25
  cluster-up/cluster/kind-1.23-sriov/provider.sh
  cluster-up/cluster/kind-1.23/provider.sh
  cluster-up/cluster/kind-1.25-vgpu/README.md
  cluster-up/cluster/kind-1.25-vgpu/config_vgpu_cluster.sh
  cluster-up/cluster/kind-1.25-vgpu/conformance.json
  cluster-up/cluster/kind-1.25-vgpu/provider.sh
  cluster-up/cluster/kind-1.25-vgpu/vgpu-node/node.sh
  cluster-up/cluster/kind/common.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#977 Enable deploying Multus V3 from manifests
  cluster-provision/k8s/1.24/k8s_provision.sh
  cluster-provision/k8s/1.24/manifests/multus/multus.yaml
  cluster-provision/k8s/1.25/k8s_provision.sh
  cluster-provision/k8s/1.25/manifests/multus/multus.yaml
  cluster-provision/k8s/1.26-centos9/k8s_provision.sh
  cluster-provision/k8s/1.26-centos9/manifests/multus/multus.yaml
  cluster-provision/k8s/check-cluster-up.sh
  cluster-provision/k8s/deploy-manifests.sh
  cluster-provision/k8s/test-multi-net.yaml
  cluster-up/cluster/k8s-provider-common.sh
Labels: size/XL, approved, lgtm, dco-signoff: yes

#980 publish: Refactor script
  publish.sh
Labels: size/L, approved, lgtm, dco-signoff: yes

#983 kind: amend env variable CONFIG_WORKER_CPU_MANAGER
  cluster-up/cluster/kind-1.23/provider.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#985 Control-plane nodes which are marked as schedulable are also given worker role.
  cluster-up/cluster/kind/common.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#990 Revert "Control-plane nodes which are marked as schedulable are also given worker role. (#985)"
  cluster-up/cluster/kind/common.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes
