Repository kubevirt/kubevirtci, pull requests merged in 2023-08, with the labels that each got.

#1066 Enable unprivileged_userfaultfd on centos 9 to support post-copy migration
  cluster-provision/k8s/1.26-centos9/k8s_provision.sh
  cluster-provision/k8s/1.27/k8s_provision.sh
  cluster-provision/k8s/1.28/k8s_provision.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#1068 Fix regex escaping in KUBEVIRT_CUSTOM_CDI_VERSION
  cluster-up/cluster/k8s-provider-common.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1069 Upgrade the 1.28 provider to the rc.1
  cluster-provision/k8s/1.28/version
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1070 Upgrade k8s-1.28 provider to stable release 1.28.0
  cluster-provision/k8s/1.28/node01.sh
  cluster-provision/k8s/1.28/version
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1071 kind, vgpu: Remove old kind-1.25-vgpu
  cluster-up/cluster/kind-1.25-vgpu/config_vgpu_cluster.sh
  cluster-up/cluster/kind-1.25-vgpu/conformance.json
  cluster-up/cluster/kind-1.25-vgpu/provider.sh
  cluster-up/cluster/kind-1.25-vgpu/vgpu-node/node.sh
Labels: size/L, approved, lgtm, dco-signoff: yes

#1075 Pin to earlier versions of vmlinuz and initrd.img due to issue with latest
  cluster-provision/centos9/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1072 Increase default disk size to avoid node disk pressure
  cluster-provision/centos9/scripts/vm.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes
