Repository kubevirt/kubevirtci, pull requests merged in 2023-01, with the labels that each got.

#937 centos9: update to 20221219.0
  cluster-provision/centos9/version
Labels: size/XS, approved, lgtm, dco-signoff: yes

#943 Add documentation about swap enablement on kubevirtci
  KUBEVIRTCI_LOCAL_TESTING.md
Labels: size/S, approved, lgtm, dco-signoff: yes

#940 k8s-1.26: Use centos8 base image
  cluster-provision/k8s/1.26/base
Labels: size/XS, approved, lgtm, dco-signoff: yes

#939 Refresh snapshot CRDs
  cluster-provision/k8s/1.25-ipv6/manifests/ceph/rbac-snapshot-controller.yaml
  cluster-provision/k8s/1.25-ipv6/manifests/ceph/setup-snapshot-controller.yaml
  cluster-provision/k8s/1.25-ipv6/manifests/ceph/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  cluster-provision/k8s/1.25-ipv6/manifests/ceph/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  cluster-provision/k8s/1.25-ipv6/manifests/ceph/snapshot.storage.k8s.io_volumesnapshots.yaml
  cluster-provision/k8s/1.25/manifests/ceph/rbac-snapshot-controller.yaml
  cluster-provision/k8s/1.25/manifests/ceph/setup-snapshot-controller.yaml
  cluster-provision/k8s/1.25/manifests/ceph/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  cluster-provision/k8s/1.25/manifests/ceph/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  cluster-provision/k8s/1.25/manifests/ceph/snapshot.storage.k8s.io_volumesnapshots.yaml
  cluster-provision/k8s/1.26/manifests/ceph/rbac-snapshot-controller.yaml
  cluster-provision/k8s/1.26/manifests/ceph/setup-snapshot-controller.yaml
  cluster-provision/k8s/1.26/manifests/ceph/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  cluster-provision/k8s/1.26/manifests/ceph/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  cluster-provision/k8s/1.26/manifests/ceph/snapshot.storage.k8s.io_volumesnapshots.yaml
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#942 Ksm support in kubevirtci
  KUBEVIRTCI_LOCAL_TESTING.md
  cluster-up/cluster/k8s-provider-common.sh
  cluster-up/hack/common.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#944 Update provisioning container image to Fedora 37
  cluster-provision/centos8/Dockerfile
  cluster-provision/centos9/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#950 Enable PSA on 1.26 providers
  cluster-provision/k8s/1.26-centos9/k8s_provision.sh
  cluster-provision/k8s/1.26-centos9/manifests/kubeadm.conf
  cluster-provision/k8s/1.26-centos9/manifests/kubeadm_ipv6.conf
  cluster-provision/k8s/1.26-centos9/psa.sh
  cluster-provision/k8s/1.26/k8s_provision.sh
  cluster-provision/k8s/1.26/manifests/kubeadm.conf
  cluster-provision/k8s/1.26/manifests/kubeadm_ipv6.conf
  cluster-provision/k8s/1.26/psa.sh
Labels: size/L, approved, lgtm, dco-signoff: yes

#948 cluster-up: Introduce and support KUBEVIRT_DEPLOY_CDI_LATEST
  cluster-up/cluster/k8s-provider-common.sh
  cluster-up/hack/common.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#952 Upgrade 1.26 providers to use crio version 1.26
  cluster-provision/k8s/1.26-centos9/provision.sh
  cluster-provision/k8s/1.26/provision.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#949 kind-1.23-vgpu: use CRI_BIN instead of hardcoded docker calls
  cluster-up/cluster/kind-1.23-vgpu/provider.sh
  cluster-up/cluster/kind-1.23-vgpu/vgpu-node/node.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes
