Repository kubevirt/kubevirtci, pull requests merged in 2023-06, with the labels that each got.

#1015 vm based providers: Add enable audit flag
  cluster-provision/gocli/cmd/run.go
  cluster-provision/k8s/1.25/node01.sh
  cluster-provision/k8s/1.26-centos9/node01.sh
  cluster-provision/k8s/1.27/node01.sh
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/hack/common.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#1023 vm based: Skip presubmit according provision manager
  cluster-provision/k8s/provision.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#1026 vpgu: Bump kind to v0.18.0, k8s-1.27.1
  cluster-up/cluster/README_VGPU.md
  cluster-up/cluster/kind-1.27-vgpu/config_vgpu_cluster.sh
  cluster-up/cluster/kind-1.27-vgpu/conformance.json
  cluster-up/cluster/kind-1.27-vgpu/provider.sh
  cluster-up/cluster/kind-1.27-vgpu/vgpu-node/node.sh
Labels: size/L, approved, lgtm, dco-signoff: yes

#1029 k8s-1.27: Bump CRIO
  cluster-provision/k8s/1.27/provision.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1032 Fix duplicate mount error during provisioning
  cluster-provision/gocli/cmd/provision.go
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1030 pman: Update info about BYPASS_PMAN_CHANGE_CHECK
  KUBEVIRTCI_LOCAL_TESTING.md
  cluster-provision/k8s/provision.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1024 Bump provisioning image to fedora 38
  cluster-provision/centos8/Dockerfile
  cluster-provision/centos9/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#996 Provide usbs into VMs
  cluster-provision/centos9/scripts/vm.sh
  cluster-provision/gocli/cmd/run.go
Labels: size/M, approved, lgtm, dco-signoff: yes

#1034 centos9: drop elevator kernel command-line
  cluster-provision/centos9/scripts/kernel.args
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1033 Allow deploying custom CDI version
  cluster-up/cluster/k8s-provider-common.sh
  cluster-up/hack/common.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#732 enable vm-image-builder to build Arm64 images
  cluster-provision/images/vm-image-builder/README.md
  cluster-provision/images/vm-image-builder/alpine-cloud-init/create-image.sh
  cluster-provision/images/vm-image-builder/common.sh
  cluster-provision/images/vm-image-builder/create-containerdisk.sh
  cluster-provision/images/vm-image-builder/customize-image.sh
  cluster-provision/images/vm-image-builder/example/image-url-arm64
  cluster-provision/images/vm-image-builder/fedora-kubeadm/image-url-arm64
  cluster-provision/images/vm-image-builder/fedora-kubeadm/os-variant
  cluster-provision/images/vm-image-builder/fedora-realtime/image-url-arm64
  cluster-provision/images/vm-image-builder/fedora-with-test-tooling/image-url-arm64
  cluster-provision/images/vm-image-builder/publish-containerdisk.sh
  cluster-provision/images/vm-image-builder/publish-multiarch-containerdisk.sh
Labels: size/L, approved, lgtm, dco-signoff: yes
