Repository kubevirt/kubevirtci, pull requests merged in 2023-02, with the labels that each got.

#953 Apply fix to issue pulling the coredns image for 1.24
  cluster-provision/k8s/1.24/extra-pre-pull-images
  cluster-provision/k8s/1.24/k8s_provision.sh
  cluster-provision/k8s/1.24/version
  cluster-provision/k8s/1.25/version
  cluster-provision/k8s/1.26/version
Labels: size/S, approved, lgtm, dco-signoff: yes

#956 k8s-1.24-psa: Remove leftovers
  cluster-up/cluster/k8s-1.24-psa/provider.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#960 Enable Seccomp configuration
  cluster-provision/k8s/check-cluster-up.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#947 Refresh snapshot CRDs follow up for 1.26-centos9 provider
  cluster-provision/k8s/1.26-centos9/manifests/ceph/rbac-snapshot-controller.yaml
  cluster-provision/k8s/1.26-centos9/manifests/ceph/setup-snapshot-controller.yaml
  cluster-provision/k8s/1.26-centos9/manifests/ceph/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  cluster-provision/k8s/1.26-centos9/manifests/ceph/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  cluster-provision/k8s/1.26-centos9/manifests/ceph/snapshot.storage.k8s.io_volumesnapshots.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#968 centos8: set SELinux boolean that is now required for chardev access by containers
  cluster-provision/k8s/1.24/provision.sh
  cluster-provision/k8s/1.25/provision.sh
  cluster-provision/k8s/1.26/provision.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#967 Add WFFC variation of rook-ceph-block
  cluster-provision/k8s/1.24/manifests/ceph/storageclass-test.yaml
  cluster-provision/k8s/1.25/manifests/ceph/storageclass-test.yaml
  cluster-provision/k8s/1.26-centos9/manifests/ceph/storageclass-test.yaml
  cluster-provision/k8s/1.26/manifests/ceph/storageclass-test.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#970 robust stack: Fix presubmit sanity check
  cluster-provision/k8s/check-cluster-up.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes
