Repository kubevirt/kubevirtci, pull requests merged in 2024-11, with the labels that each got.

#1286 kind-1.28: add conformance.json
  cluster-up/cluster/kind-1.28/conformance.json
Labels: size/M, approved, lgtm, dco-signoff: yes

#1320 crio: pin cri-o to previous minor version for each provider
  cluster-provision/k8s/1.29/k8s_provision.sh
  cluster-provision/k8s/1.30/k8s_provision.sh
  cluster-provision/k8s/1.31/k8s_provision.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes, kind/failing-test

#1252 K8s 1.30 provider slim s390x
  K8S.md
  KUBEVIRTCI_LOCAL_TESTING.md
  cluster-provision/centos9/Dockerfile
  cluster-provision/centos9/build.sh
  cluster-provision/centos9/scripts/download_box.sh
  cluster-provision/centos9/scripts/kernel.s390x.args
  cluster-provision/centos9/scripts/vm.sh
  cluster-provision/gocli/Makefile
  cluster-provision/gocli/cmd/provision.go
  cluster-provision/gocli/cmd/run.go
  cluster-provision/gocli/cmd/scp.go
  cluster-provision/gocli/cmd/utils/images.go
  cluster-provision/gocli/opts/node01/node01.go
  cluster-provision/gocli/opts/nodes/nodes.go
  cluster-provision/gocli/opts/nodes/testconfig.go
  cluster-provision/gocli/pkg/libssh/ssh.go
  cluster-provision/k8s/1.30/k8s_provision.sh
  cluster-provision/k8s/1.30/provision.sh
  cluster-provision/k8s/base-image
  cluster-provision/k8s/check-cluster-up.sh
  cluster-up/check.sh
  cluster-up/cluster/k8s-provider-common.sh
  hack/conformance.sh
  publish.sh
Labels: size/XL, approved, lgtm, dco-signoff: yes, sig/ci

#1316 K8s 1.31 provider slim support for s390x arch
  cluster-provision/k8s/1.31/k8s_provision.sh
  cluster-provision/k8s/1.31/provision.sh
  publish.sh
Labels: size/M, kind/enhancement, approved, lgtm, dco-signoff: yes, sig/buildsystem

#1322 Publish centos9 built from latest provider
  publish.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1321 kind-sriov: Bump node image to k8s-1.31
  cluster-up/cluster/kind-sriov/image
  cluster-up/cluster/kind-sriov/version
Labels: size/XS, approved, lgtm, dco-signoff: yes, sig/buildsystem

#1328 fix: IMAGES_TO_BUILD format in publish script
  publish.sh
Labels: size/XS, kind/bug, approved, lgtm, dco-signoff: yes, sig/buildsystem
