Repository kubevirt/kubevirtci, pull requests merged in 2024-05, with the labels that each got.

#1188 cluster-up: Update default provider to k8s-1.30
  K8S.md
  KUBEVIRTCI_LOCAL_TESTING.md
  cluster-up/hack/common.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#1186 k8s-1.30: Upgrade crio to v1.30
  cluster-provision/k8s/1.30/k8s_provision.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1194 cluster-up: Remove unrequired check
  cluster-up/up.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1184 cluster-up, cnao: Do not deploy OVS-CNI
  cluster-provision/k8s/1.28/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.29/manifests/cnao/network-addons-config-example.cr.yaml
  cluster-provision/k8s/1.30/manifests/cnao/network-addons-config-example.cr.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1193 kind-ovn: Introduce new kind-ovn provider
  cluster-up/cluster/kind-ovn/README.md
  cluster-up/cluster/kind-ovn/install-ovn.sh
  cluster-up/cluster/kind-ovn/provider.sh
Labels: size/L, approved, lgtm, dco-signoff: yes

#1178 add ability to deploy kwok when KUBEVIRT_DEPLOY_KWOK is set to true
  cluster-provision/gocli/cmd/provision.go
  cluster-provision/k8s/1.28/k8s_provision.sh
  cluster-provision/k8s/1.28/manifests/kwok/kubevirt/kustomization.yaml
  cluster-provision/k8s/1.28/manifests/kwok/kubevirt/rbac/kustomization.yaml
  cluster-provision/k8s/1.28/manifests/kwok/kubevirt/rbac/role-binding.yaml
  cluster-provision/k8s/1.28/manifests/kwok/kubevirt/rbac/role.yaml
  cluster-provision/k8s/1.28/manifests/kwok/kubevirt/stage/kustomization.yaml
  cluster-provision/k8s/1.28/manifests/kwok/kubevirt/stage/vmi-delete.yaml
  cluster-provision/k8s/1.28/manifests/kwok/kubevirt/stage/vmi-ready.yaml
  cluster-provision/k8s/1.28/manifests/kwok/kwok.yaml
  cluster-provision/k8s/1.28/manifests/kwok/stage-fast.yaml
  cluster-provision/k8s/1.29/k8s_provision.sh
  cluster-provision/k8s/1.29/manifests/kwok/kubevirt/kustomization.yaml
  cluster-provision/k8s/1.29/manifests/kwok/kubevirt/rbac/kustomization.yaml
  cluster-provision/k8s/1.29/manifests/kwok/kubevirt/rbac/role-binding.yaml
  cluster-provision/k8s/1.29/manifests/kwok/kubevirt/rbac/role.yaml
  cluster-provision/k8s/1.29/manifests/kwok/kubevirt/stage/kustomization.yaml
  cluster-provision/k8s/1.29/manifests/kwok/kubevirt/stage/vmi-delete.yaml
  cluster-provision/k8s/1.29/manifests/kwok/kubevirt/stage/vmi-ready.yaml
  cluster-provision/k8s/1.29/manifests/kwok/kwok.yaml
  cluster-provision/k8s/1.29/manifests/kwok/stage-fast.yaml
  cluster-provision/k8s/1.30/k8s_provision.sh
  cluster-provision/k8s/1.30/manifests/kwok/kubevirt/kustomization.yaml
  cluster-provision/k8s/1.30/manifests/kwok/kubevirt/rbac/kustomization.yaml
  cluster-provision/k8s/1.30/manifests/kwok/kubevirt/rbac/role-binding.yaml
  cluster-provision/k8s/1.30/manifests/kwok/kubevirt/rbac/role.yaml
  cluster-provision/k8s/1.30/manifests/kwok/kubevirt/stage/kustomization.yaml
  cluster-provision/k8s/1.30/manifests/kwok/kubevirt/stage/vmi-delete.yaml
  cluster-provision/k8s/1.30/manifests/kwok/kubevirt/stage/vmi-ready.yaml
  cluster-provision/k8s/1.30/manifests/kwok/kwok.yaml
  cluster-provision/k8s/1.30/manifests/kwok/stage-fast.yaml
  cluster-provision/k8s/check-cluster-up.sh
  cluster-provision/k8s/deploy-manifests.sh
  cluster-up/cluster/k8s-provider-common.sh
  hack/bump-kwok.sh
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#1196 kind-ovn: Fix cluster-down function
  cluster-up/cluster/kind-ovn/provider.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1198 kind-ovn: Avoid failing entire run just because tear down error
  cluster-up/cluster/kind-ovn/provider.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes
