Repository kubevirt/kubevirtci, pull requests merged in 2024-07, with the labels that each got.

#1215 vm based: Bump CNAO to 0.94.1
  cluster-provision/k8s/1.28/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.28/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.29/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.29/manifests/cnao/operator.yaml
  cluster-provision/k8s/1.30/manifests/cnao/network-addons-config.crd.yaml
  cluster-provision/k8s/1.30/manifests/cnao/operator.yaml
  hack/bump-cnao.sh
Labels: size/L, approved, lgtm, dco-signoff: yes

#1207 enable vm-image-builder for s390x.
  cluster-provision/images/vm-image-builder/README.md
  cluster-provision/images/vm-image-builder/common.sh
  cluster-provision/images/vm-image-builder/example/image-url-s390x
  cluster-provision/images/vm-image-builder/fedora-kubeadm/image-url-s390x
  cluster-provision/images/vm-image-builder/fedora-realtime/image-url-s390x
  cluster-provision/images/vm-image-builder/fedora-with-test-tooling/cloud-config
  cluster-provision/images/vm-image-builder/fedora-with-test-tooling/image-url-s390x
  cluster-provision/images/vm-image-builder/publish-multiarch-containerdisk.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#1216 Fix missing whitespace in check script
  cluster-up/check.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1209 Library based ssh
  cluster-provision/gocli/cmd/cmd_suite_test.go
  cluster-provision/gocli/cmd/nodesconfig/nodeconfig.go
  cluster-provision/gocli/cmd/run.go
  cluster-provision/gocli/cmd/run_test.go
  cluster-provision/gocli/docker/adapter.go
  cluster-provision/gocli/go.mod
  cluster-provision/gocli/go.sum
  cluster-provision/gocli/pkg/libssh/key.pem
  cluster-provision/gocli/pkg/libssh/ssh.go
  cluster-provision/gocli/utils/mock/mock_ssh.go
  cluster-provision/gocli/vendor/github.com/davecgh/go-spew/LICENSE
  cluster-provision/gocli/vendor/github.com/davecgh/go-spew/spew/bypass.go
  cluster-provision/gocli/vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  cluster-provision/gocli/vendor/github.com/davecgh/go-spew/spew/common.go
  cluster-provision/gocli/vendor/github.com/davecgh/go-spew/spew/config.go
  cluster-provision/gocli/vendor/github.com/davecgh/go-spew/spew/doc.go
  cluster-provision/gocli/vendor/github.com/davecgh/go-spew/spew/dump.go
  cluster-provision/gocli/vendor/github.com/davecgh/go-spew/spew/format.go
  cluster-provision/gocli/vendor/github.com/davecgh/go-spew/spew/spew.go
  cluster-provision/gocli/vendor/github.com/pmezard/go-difflib/LICENSE
  cluster-provision/gocli/vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  cluster-provision/gocli/vendor/github.com/stretchr/testify/LICENSE
  cluster-provision/gocli/vendor/github.com/stretchr/testify/assert/assertion_compare.go
  cluster-provision/gocli/vendor/github.com/stretchr/testify/assert/assertion_format.go
  cluster-provision/gocli/vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  cluster-provision/gocli/vendor/github.com/stretchr/testify/assert/assertion_forward.go
  cluster-provision/gocli/vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  cluster-provision/gocli/vendor/github.com/stretchr/testify/assert/assertion_order.go
  cluster-provision/gocli/vendor/github.com/stretchr/testify/assert/assertions.go
  cluster-provision/gocli/vendor/github.com/stretchr/testify/assert/doc.go
  cluster-provision/gocli/vendor/github.com/stretchr/testify/assert/errors.go
  cluster-provision/gocli/vendor/github.com/stretchr/testify/assert/forward_assertions.go
  cluster-provision/gocli/vendor/github.com/stretchr/testify/assert/http_assertions.go
  cluster-provision/gocli/vendor/github.com/stretchr/testify/require/doc.go
  cluster-provision/gocli/vendor/github.com/stretchr/testify/require/forward_requirements.go
  cluster-provision/gocli/vendor/github.com/stretchr/testify/require/require.go
  cluster-provision/gocli/vendor/github.com/stretchr/testify/require/require.go.tmpl
  cluster-provision/gocli/vendor/github.com/stretchr/testify/require/require_forward.go
  cluster-provision/gocli/vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  cluster-provision/gocli/vendor/github.com/stretchr/testify/require/requirements.go
  cluster-provision/gocli/vendor/github.com/stretchr/testify/suite/doc.go
  cluster-provision/gocli/vendor/github.com/stretchr/testify/suite/interfaces.go
  cluster-provision/gocli/vendor/github.com/stretchr/testify/suite/stats.go
  cluster-provision/gocli/vendor/github.com/stretchr/testify/suite/suite.go
  cluster-provision/gocli/vendor/go.uber.org/mock/AUTHORS
  cluster-provision/gocli/vendor/go.uber.org/mock/LICENSE
  cluster-provision/gocli/vendor/go.uber.org/mock/gomock/call.go
  cluster-provision/gocli/vendor/go.uber.org/mock/gomock/callset.go
  cluster-provision/gocli/vendor/go.uber.org/mock/gomock/controller.go
  cluster-provision/gocli/vendor/go.uber.org/mock/gomock/doc.go
  cluster-provision/gocli/vendor/go.uber.org/mock/gomock/matchers.go
  cluster-provision/gocli/vendor/modules.txt
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#1218 alpine,image: Use full image name for qemu-user-static image
  cluster-provision/images/vm-image-builder/alpine-cloud-init/create-image.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1223 fix: Run etcd mount commands with sudo
  cluster-provision/gocli/cmd/run.go
  cluster-provision/gocli/cmd/run_test.go
Labels: size/S, approved, lgtm, dco-signoff: yes

#1227 kubevirtci, OWNERS: add OWNERS files wrt sigs
  OWNERS
  OWNERS_ALIASES
  cluster-provision/k8s/1.31/OWNERS
  cluster-up/cluster/OWNERS
  hack/pman/rules.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#1231 OWNERS: add xpivarc as approver for kubevirtci
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm, dco-signoff: yes
