Repository kubevirt/kubevirtci, pull requests merged in 2024-02, with the labels that each got.

#1131 bump kind script: Fix script and generalize it
  cluster-up/cluster/kind-1.27-vgpu/image
  cluster-up/cluster/kind-1.27-vgpu/provider.sh
  cluster-up/cluster/kind-1.27-vgpu/version
  cluster-up/cluster/kind-1.28/image
  cluster-up/cluster/kind-1.28/provider.sh
  cluster-up/cluster/kind-1.28/version
  cluster-up/cluster/kind/bump-kind.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#1130 kind,sriov: Remove old provider
  cluster-up/cluster/kind-1.27-sriov/OWNERS
  cluster-up/cluster/kind-1.27-sriov/README.md
  cluster-up/cluster/kind-1.27-sriov/TROUBLESHOOTING.md
  cluster-up/cluster/kind-1.27-sriov/config_sriov_cluster.sh
  cluster-up/cluster/kind-1.27-sriov/conformance.json
  cluster-up/cluster/kind-1.27-sriov/provider.sh
  cluster-up/cluster/kind-1.27-sriov/sriov-components/manifests/kustomization.yaml
  cluster-up/cluster/kind-1.27-sriov/sriov-components/manifests/multus/kustomization.yaml
  cluster-up/cluster/kind-1.27-sriov/sriov-components/manifests/multus/multus.yaml
  cluster-up/cluster/kind-1.27-sriov/sriov-components/manifests/multus/patch-args.yaml
  cluster-up/cluster/kind-1.27-sriov/sriov-components/manifests/patch-node-selector.yaml.in
  cluster-up/cluster/kind-1.27-sriov/sriov-components/manifests/patch-sriovdp-resource-prefix.yaml.in
  cluster-up/cluster/kind-1.27-sriov/sriov-components/manifests/sriov-cni-daemonset.yaml
  cluster-up/cluster/kind-1.27-sriov/sriov-components/manifests/sriov-ns.yaml
  cluster-up/cluster/kind-1.27-sriov/sriov-components/manifests/sriovdp-config.yaml.in
  cluster-up/cluster/kind-1.27-sriov/sriov-components/manifests/sriovdp-daemonset.yaml
  cluster-up/cluster/kind-1.27-sriov/sriov-components/sriov_components.sh
  cluster-up/cluster/kind-1.27-sriov/sriov-node/configure_vfs.sh
  cluster-up/cluster/kind-1.27-sriov/sriov-node/node.sh
  cluster-up/cluster/kind-1.27-sriov/sriovdp_setup.sh
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#1135 Upgrade centos9 stream base nodes VM image
  cluster-provision/centos9/version
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1132 Configure Prometheus to select kubevirt prometheusrules
  cluster-up/cluster/k8s-provider-common.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1139 Fix Prometheus config
  cluster-up/cluster/k8s-provider-common.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1143 k8s-1.30: Update kubernetes version to v1.30.0-alpha.2
  cluster-provision/k8s/1.30/version
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1140 Build kubevirtci nodes from static centos stream base image
  cluster-provision/gocli/cmd/provision.go
  cluster-provision/k8s/1.27/k8s_provision.sh
  cluster-provision/k8s/1.27/provision.sh
  cluster-provision/k8s/1.28/k8s_provision.sh
  cluster-provision/k8s/1.28/provision.sh
  cluster-provision/k8s/1.29/k8s_provision.sh
  cluster-provision/k8s/1.29/provision.sh
  cluster-provision/k8s/1.30/k8s_provision.sh
  cluster-provision/k8s/1.30/provision.sh
  cluster-provision/k8s/base-image
  publish.sh
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#1145 centos,base: Follow up changes to tidy up some leftovers
  cluster-provision/k8s/1.27/provision.sh
  cluster-provision/k8s/1.28/provision.sh
  cluster-provision/k8s/provision.sh
  publish.sh
Labels: size/M, approved, lgtm, dco-signoff: yes
