Repository kubevirt/kubevirtci, pull requests merged in 2025-09, with the labels that each got.

#1506 vm based providers: Introduce Flannel CNI
  cluster-provision/gocli/cmd/nodesconfig/nodeconfig.go
  cluster-provision/gocli/cmd/nodesconfig/opts.go
  cluster-provision/gocli/cmd/run.go
  cluster-provision/gocli/opts/node01/node01.go
  cluster-provision/gocli/opts/node01/node01_test.go
  cluster-provision/k8s/1.31/extra-pre-pull-images
  cluster-provision/k8s/1.31/k8s_provision.sh
  cluster-provision/k8s/1.31/manifests/flannel.diff
  cluster-provision/k8s/1.31/manifests/flannel.do-not-change.yaml
  cluster-provision/k8s/1.31/manifests/flannel_ipv6.diff
  cluster-provision/k8s/1.31/manifests/knp.diff
  cluster-provision/k8s/1.31/manifests/knp.do-not-change.yaml
  cluster-provision/k8s/1.31/manifests/kubeadm_flannel.conf
  cluster-provision/k8s/1.31/manifests/kubeadm_flannel_ipv6.conf
  cluster-provision/k8s/1.31/pre-pull-images
  cluster-provision/k8s/1.32/extra-pre-pull-images
  cluster-provision/k8s/1.32/k8s_provision.sh
  cluster-provision/k8s/1.32/manifests/flannel.diff
  cluster-provision/k8s/1.32/manifests/flannel.do-not-change.yaml
  cluster-provision/k8s/1.32/manifests/flannel_ipv6.diff
  cluster-provision/k8s/1.32/manifests/knp.diff
  cluster-provision/k8s/1.32/manifests/knp.do-not-change.yaml
  cluster-provision/k8s/1.32/manifests/kubeadm_flannel.conf
  cluster-provision/k8s/1.32/manifests/kubeadm_flannel_ipv6.conf
  cluster-provision/k8s/1.32/pre-pull-images
  cluster-provision/k8s/1.33/extra-pre-pull-images
  cluster-provision/k8s/1.33/k8s_provision.sh
  cluster-provision/k8s/1.33/manifests/flannel.diff
  cluster-provision/k8s/1.33/manifests/flannel.do-not-change.yaml
  cluster-provision/k8s/1.33/manifests/flannel_ipv6.diff
  cluster-provision/k8s/1.33/manifests/knp.diff
  cluster-provision/k8s/1.33/manifests/knp.do-not-change.yaml
  cluster-provision/k8s/1.33/manifests/kubeadm_flannel.conf
  cluster-provision/k8s/1.33/manifests/kubeadm_flannel_ipv6.conf
  cluster-provision/k8s/1.33/pre-pull-images
  cluster-provision/k8s/1.34/extra-pre-pull-images
  cluster-provision/k8s/1.34/k8s_provision.sh
  cluster-provision/k8s/1.34/manifests/flannel.diff
  cluster-provision/k8s/1.34/manifests/flannel.do-not-change.yaml
  cluster-provision/k8s/1.34/manifests/flannel_ipv6.diff
  cluster-provision/k8s/1.34/manifests/knp.diff
  cluster-provision/k8s/1.34/manifests/knp.do-not-change.yaml
  cluster-provision/k8s/1.34/manifests/kubeadm_flannel.conf
  cluster-provision/k8s/1.34/manifests/kubeadm_flannel_ipv6.conf
  cluster-provision/k8s/1.34/pre-pull-images
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/hack/common.sh
  cluster-up/up.sh
Labels: size/XXL, sig/network, approved, lgtm, dco-signoff: yes

#1529 Publish 1.34 provider instead of 1.31 provider for s390x
  cluster-up/hack/common.sh
  publish.sh
Labels: size/S, approved, lgtm, dco-signoff: yes, wg/arch-s390x

#1541 kind: Introduce v1.34
  cluster-up/cluster/kind-1.34/README.md
  cluster-up/cluster/kind-1.34/conformance.json
  cluster-up/cluster/kind-1.34/image
  cluster-up/cluster/kind-1.34/provider.sh
  cluster-up/cluster/kind-1.34/version
Labels: size/L, kind/enhancement, approved, lgtm, dco-signoff: yes
