Repository kubevirt/kubevirtci, pull requests merged in 2025-07, with the labels that each got.

#1468 Add an alias to KUBEVIRT_WITH_MULTUS_V3
  cluster-provision/k8s/check-cluster-up.sh
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: size/XS, kind/enhancement, approved, lgtm, dco-signoff: yes

#1470 kind-ovn: Consume fix for working with local registry when using podman
  cluster-up/cluster/kind-ovn/install-ovn.sh
  cluster-up/cluster/kind-ovn/provider.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#1475 Continue the fix of the issue with job names w/o k8s version
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: size/XS, kind/bug, approved, lgtm, dco-signoff: yes

#1467 fix(check-pod-images.sh): use pre-pull-images, add --auto-update
  cluster-provision/k8s/check-pod-images.sh
Labels: size/M, kind/enhancement, approved, lgtm, dco-signoff: yes

#1482 cluster-up/cluster/kind/common.sh: remove ppc64le arch support
  cluster-up/cluster/kind/common.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes, kind/cleanup

#1485 vm based providers: Bump CNAO to v0.100.0-rc0
  cluster-provision/gocli/opts/cnao/manifests/operator.yaml
  cluster-provision/k8s/1.31/extra-pre-pull-images
  cluster-provision/k8s/1.31/pre-pull-images
  cluster-provision/k8s/1.32/extra-pre-pull-images
  cluster-provision/k8s/1.32/pre-pull-images
  cluster-provision/k8s/1.33/extra-pre-pull-images
  cluster-provision/k8s/1.33/pre-pull-images
Labels: size/L, kind/enhancement, approved, lgtm, dco-signoff: yes

#1493 kind-1.30-vgpu: Remove provider as kubernetes v1.30 is no longer support in kubevirt
  cluster-up/cluster/kind-1.30-vgpu/config_vgpu_cluster.sh
  cluster-up/cluster/kind-1.30-vgpu/conformance.json
  cluster-up/cluster/kind-1.30-vgpu/image
  cluster-up/cluster/kind-1.30-vgpu/provider.sh
  cluster-up/cluster/kind-1.30-vgpu/version
  cluster-up/cluster/kind-1.30-vgpu/vgpu-node/node.sh
Labels: size/L, approved, lgtm, dco-signoff: yes, kind/cleanup

#1495 k8s-1.34: Add new cluster provider for Kubernetes v1.34
  cluster-provision/k8s/1.34/base
  cluster-provision/k8s/1.34/conformance.json
  cluster-provision/k8s/1.34/extra-pre-pull-images
  cluster-provision/k8s/1.34/istio.sh
  cluster-provision/k8s/1.34/k8s_provision.sh
  cluster-provision/k8s/1.34/manifests/cni.diff
  cluster-provision/k8s/1.34/manifests/cni.do-not-change.yaml
  cluster-provision/k8s/1.34/manifests/cni_ipv6.diff
  cluster-provision/k8s/1.34/manifests/kubeadm.conf
  cluster-provision/k8s/1.34/manifests/kubeadm_ipv6.conf
  cluster-provision/k8s/1.34/manifests/kwok/kubevirt/kustomization.yaml
  cluster-provision/k8s/1.34/manifests/kwok/kubevirt/rbac/kustomization.yaml
  cluster-provision/k8s/1.34/manifests/kwok/kubevirt/rbac/role-binding.yaml
  cluster-provision/k8s/1.34/manifests/kwok/kubevirt/rbac/role.yaml
  cluster-provision/k8s/1.34/manifests/kwok/kubevirt/stage/kustomization.yaml
  cluster-provision/k8s/1.34/manifests/kwok/kubevirt/stage/vmi-delete.yaml
  cluster-provision/k8s/1.34/manifests/kwok/kubevirt/stage/vmi-ready.yaml
  cluster-provision/k8s/1.34/manifests/kwok/kwok.yaml
  cluster-provision/k8s/1.34/manifests/kwok/stage-fast.yaml
  cluster-provision/k8s/1.34/manifests/local-volume.yaml
  cluster-provision/k8s/1.34/manifests/nodeports/monitoring.yaml
  cluster-provision/k8s/1.34/pre-pull-images
  cluster-provision/k8s/1.34/provision.sh
  cluster-provision/k8s/1.34/version
  cluster-up/cluster/k8s-1.34/provider.sh
Labels: size/XXL, kind/enhancement, approved, lgtm, dco-signoff: yes
