Repository kubevirt/kubevirtci, pull requests merged in 2025-06, with the labels that each got.

#1448 [VEP-10]: add kind-1.32-dra provider
  cluster-up/cluster/kind-1.32-dra/README.md
  cluster-up/cluster/kind-1.32-dra/conformance.json
  cluster-up/cluster/kind-1.32-dra/image
  cluster-up/cluster/kind-1.32-dra/kind.yaml
  cluster-up/cluster/kind-1.32-dra/provider.sh
  cluster-up/cluster/kind-1.32-dra/version
Labels: size/L, kind/enhancement, approved, lgtm, dco-signoff: yes, sig/buildsystem

#1437 Set permissions for .kubectl and .kubeconfig with k8s-* provider and Docker CRI
  cluster-up/cluster/k8s-provider-common.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#1456 k8s,provision: Update cri-o repo location to match new path in mirror
  cluster-provision/k8s/1.30/k8s_provision.sh
  cluster-provision/k8s/1.31/k8s_provision.sh
  cluster-provision/k8s/1.32/k8s_provision.sh
  cluster-provision/k8s/1.33/k8s_provision.sh
Labels: size/S, kind/enhancement, approved, lgtm, dco-signoff: yes

#1446 docs: Adding Podman PID limitation documentation
  PODMAN.md
Labels: size/S, approved, lgtm, dco-signoff: yes, do-not-merge/invalid-commit-message, sig/documentation

#1461 fix(fg): set DisableCPUQuotaWithExclusiveCPUs false for 1.33
  cluster-provision/k8s/1.33/k8s_provision.sh
Labels: size/XS, kind/bug, approved, lgtm, dco-signoff: yes
