Repository kubevirt/kubevirtci, pull requests merged in 2025-02, with the labels that each got.

#1289 k8s-provider: Remove KUBEVIRT_CPU_MANAGER_POLICY
  cluster-provision/gocli/opts/nodes/nodes.go
  cluster-provision/gocli/opts/nodes/testconfig.go
  cluster-up/cluster/k8s-provider-common.sh
  cluster-up/cluster/kind/common.sh
  cluster-up/hack/common.sh
Labels: size/S, approved, lgtm, dco-signoff: yes, kind/cleanup

#1365 kind-sriov: Bump SR-IOV CNI and device-plugin
  cluster-up/cluster/kind-sriov/sriov-components/manifests/kustomization.yaml
  cluster-up/cluster/kind-sriov/sriov-components/manifests/patch-node-selector.yaml.in
  cluster-up/cluster/kind-sriov/sriov-components/manifests/sriov-cni-daemonset.yaml
  cluster-up/cluster/kind-sriov/sriov-components/manifests/sriovdp-daemonset.yaml
Labels: size/L, kind/enhancement, approved, lgtm, dco-signoff: yes

#1363 vm based: Add retry to kubeadm init
  cluster-provision/k8s/1.30/k8s_provision.sh
  cluster-provision/k8s/1.31/k8s_provision.sh
  cluster-provision/k8s/1.32/k8s_provision.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#1366 fix: remove the gocli container after running make container-run
  cluster-provision/gocli/Makefile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1343 Revert cri-o freeze
  cluster-provision/k8s/1.30/k8s_provision.sh
  cluster-provision/k8s/1.31/k8s_provision.sh
  cluster-provision/k8s/1.32/k8s_provision.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1370 k8s-1.32: Update to use cri-o v1.32
  cluster-provision/k8s/1.32/k8s_provision.sh
Labels: size/XS, kind/enhancement, approved, lgtm, dco-signoff: yes

#1371 ceph: Increase timeout for ceph to be ready to 10 minutes
  cluster-provision/gocli/opts/rookceph/ceph.go
Labels: size/XS, sig/storage, approved, lgtm, dco-signoff: yes, sig/ci

#1373 prepull images: update extra-pre-pull-images with missing images required for cluster-up
  cluster-provision/k8s/1.30/extra-pre-pull-images
  cluster-provision/k8s/1.31/extra-pre-pull-images
  cluster-provision/k8s/1.32/extra-pre-pull-images
Labels: size/L, kind/enhancement, approved, lgtm, dco-signoff: yes

#1368 fix: segmentation fault when using podman
  cluster-up/cluster/k8s-provider-common.sh
Labels: kind/bug, size/S, approved, lgtm, dco-signoff: yes

#1378 chore: update default kubevirt_provider.
  cluster-up/hack/common.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes, wg/arch-s390x

#1382 Make PSA on by default.
  cluster-up/hack/common.sh
Labels: size/XS, kind/enhancement, approved, lgtm, dco-signoff: yes

#1384 Revert "fix: segmentation fault when using podman (#1368)"
  cluster-up/cluster/k8s-provider-common.sh
Labels: kind/bug, size/S, approved, lgtm, dco-signoff: yes
