Repository kubevirt/kubevirtci, pull requests merged in 2025-05, with the labels that each got.

#1440 conformance: Fix filter for conformance tests after change to default behaviour
  cluster-provision/k8s/check-cluster-up.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes, kind/failing-test

#1422 istio: Remove Multus settings from the default Istio config
  cluster-provision/gocli/opts/istio/manifests/istio-operator.cr.yaml
Labels: size/XS, sig/network, approved, lgtm, dco-signoff: yes

#1408 feat: Add a new flag to configure the dynamic-networks-controller being deploy through CNAO
  cluster-provision/gocli/cmd/nodesconfig/nodeconfig.go
  cluster-provision/gocli/cmd/nodesconfig/opts.go
  cluster-provision/gocli/cmd/run.go
  cluster-provision/gocli/opts/cnao/cnao.go
  cluster-provision/gocli/opts/cnao/cnao_test.go
  cluster-up/cluster/ephemeral-provider-common.sh
Labels: size/M, kind/enhancement, sig/network, approved, lgtm, dco-signoff: yes

#1435 Export CDI upload proxy lower-band port in CI clusters
  PODMAN.md
  cluster-provision/centos9/scripts/vm.sh
  cluster-provision/gocli/cmd/ports.go
  cluster-provision/gocli/cmd/utils/ports.go
  cluster-provision/gocli/containers/dnsmasq.go
Labels: size/S, approved, lgtm, dco-signoff: yes, sig/ci

#1397 feat: enable variable for requiring nested virtualization
  cluster-up/check.sh
  cluster-up/cluster/K8S.md
Labels: size/S, kind/enhancement, approved, lgtm, dco-signoff: yes

#1442 fix: Isolate kubeconfig and control CRI via KIND_EXPERIMENTAL_PROVIDER in kind provider
  cluster-up/cluster/kind/common.sh
Labels: size/S, kind/enhancement, approved, lgtm, dco-signoff: yes

#1374 fix: use pre-generated image lists for pre-pulling images
  cluster-provision/gocli/cmd/provision.go
  cluster-provision/gocli/opts/rookceph/ceph.go
  cluster-provision/gocli/opts/rookceph/ceph_test.go
  cluster-provision/k8s/1.30/extra-pre-pull-images
  cluster-provision/k8s/1.30/k8s_provision.sh
  cluster-provision/k8s/1.30/pre-pull-images
  cluster-provision/k8s/1.31/extra-pre-pull-images
  cluster-provision/k8s/1.31/fetch-images.sh
  cluster-provision/k8s/1.31/k8s_provision.sh
  cluster-provision/k8s/1.31/pre-pull-images
  cluster-provision/k8s/1.32/extra-pre-pull-images
  cluster-provision/k8s/1.32/fetch-images.sh
  cluster-provision/k8s/1.32/k8s_provision.sh
  cluster-provision/k8s/1.32/pre-pull-images
  cluster-provision/k8s/1.33/extra-pre-pull-images
  cluster-provision/k8s/1.33/fetch-images.sh
  cluster-provision/k8s/1.33/k8s_provision.sh
  cluster-provision/k8s/1.33/pre-pull-images
  cluster-provision/k8s/check-cluster-up.sh
  cluster-provision/k8s/check-pod-images.sh
  cluster-provision/k8s/deploy-manifests.sh
  cluster-provision/k8s/fetch-images-exclude-patterns
  cluster-provision/k8s/fetch-images.sh
  cluster-provision/k8s/update-pre-pull-images.sh
Labels: size/XL, approved, lgtm, dco-signoff: yes, kind/cleanup
