Repository kubevirt/kubevirtci, pull requests merged in 2025-08, with the labels that each got.

#1508 provision: Fix pre pull lists
  cluster-provision/k8s/1.33/k8s_provision.sh
  cluster-provision/k8s/1.34/k8s_provision.sh
Labels: kind/bug, size/S, approved, lgtm, dco-signoff: yes

#1510 cnao: Bump to v0.100.0 (and fix bump script)
  cluster-provision/gocli/opts/cnao/manifests/crd.yaml
  cluster-provision/gocli/opts/cnao/manifests/operator.yaml
  cluster-provision/k8s/1.31/pre-pull-images
  cluster-provision/k8s/1.32/pre-pull-images
  cluster-provision/k8s/1.33/pre-pull-images
  cluster-provision/k8s/1.34/pre-pull-images
  hack/bump-cnao.sh
Labels: size/M, kind/enhancement, approved, lgtm, dco-signoff: yes

#1512 fix: enable resizing of xfs filesystem
  cluster-provision/k8s/1.31/provision.sh
  cluster-provision/k8s/1.32/provision.sh
  cluster-provision/k8s/1.33/provision.sh
  cluster-provision/k8s/1.34/provision.sh
Labels: kind/bug, size/M, approved, lgtm, dco-signoff: yes

#1514 cluster-up: Support global config
  K8S.md
  cluster-up/up.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#1523 images: Update missing image
  cluster-provision/k8s/1.31/extra-pre-pull-images
  cluster-provision/k8s/1.32/extra-pre-pull-images
  cluster-provision/k8s/1.33/extra-pre-pull-images
  cluster-provision/k8s/1.34/extra-pre-pull-images
Labels: size/XS, approved, lgtm, dco-signoff: yes, kind/cleanup
