Repository kubevirt/kubevirtci, pull requests merged in 2025-03, with the labels that each got.

#1388 Revert "Make PSA on by default. (#1382)"
  cluster-up/hack/common.sh
Labels: size/XS, kind/bug, approved, lgtm, dco-signoff: yes

#1387 fix: segmentation fault in podman
  cluster-up/cluster/k8s-provider-common.sh
Labels: kind/bug, size/M, approved, lgtm, dco-signoff: yes

#1392 k8s-1.33: Add new provider for Kubernetes version 1.33
  cluster-provision/k8s/1.33/base
  cluster-provision/k8s/1.33/conformance.json
  cluster-provision/k8s/1.33/extra-pre-pull-images
  cluster-provision/k8s/1.33/fetch-images.sh
  cluster-provision/k8s/1.33/istio.sh
  cluster-provision/k8s/1.33/k8s_provision.sh
  cluster-provision/k8s/1.33/manifests/cni.diff
  cluster-provision/k8s/1.33/manifests/cni.do-not-change.yaml
  cluster-provision/k8s/1.33/manifests/cni_ipv6.diff
  cluster-provision/k8s/1.33/manifests/kubeadm.conf
  cluster-provision/k8s/1.33/manifests/kubeadm_ipv6.conf
  cluster-provision/k8s/1.33/manifests/kwok/kubevirt/kustomization.yaml
  cluster-provision/k8s/1.33/manifests/kwok/kubevirt/rbac/kustomization.yaml
  cluster-provision/k8s/1.33/manifests/kwok/kubevirt/rbac/role-binding.yaml
  cluster-provision/k8s/1.33/manifests/kwok/kubevirt/rbac/role.yaml
  cluster-provision/k8s/1.33/manifests/kwok/kubevirt/stage/kustomization.yaml
  cluster-provision/k8s/1.33/manifests/kwok/kubevirt/stage/vmi-delete.yaml
  cluster-provision/k8s/1.33/manifests/kwok/kubevirt/stage/vmi-ready.yaml
  cluster-provision/k8s/1.33/manifests/kwok/kwok.yaml
  cluster-provision/k8s/1.33/manifests/kwok/stage-fast.yaml
  cluster-provision/k8s/1.33/manifests/local-volume.yaml
  cluster-provision/k8s/1.33/manifests/nodeports/monitoring.yaml
  cluster-provision/k8s/1.33/provision.sh
  cluster-provision/k8s/1.33/version
  cluster-up/cluster/k8s-1.33/provider.sh
Labels: size/XXL, kind/enhancement, approved, lgtm, dco-signoff: yes

#1396 k8s-1.33: Update url to check previous k8s version
  cluster-provision/k8s/1.33/k8s_provision.sh
Labels: size/XS, kind/bug, approved, lgtm, dco-signoff: yes

#1400 doc: Fix path to copy configs to in kubevirt directory
  KUBEVIRTCI_LOCAL_TESTING.md
Labels: size/XS, approved, lgtm, dco-signoff: yes, sig/documentation

#1376 In Provision Manager, call "git fetch --tags" command to avoid git diff fail
  cluster-provision/gocli/cmd/provision_manager.go
Labels: size/S, approved, lgtm, dco-signoff: yes, wg/arch-s390x

#1401 Bump NFS CSI to latest
  cluster-provision/gocli/opts/nfscsi/manifests/csi-nfs-controller-rbac.yaml
  cluster-provision/gocli/opts/nfscsi/manifests/csi-nfs-controller.yaml
  cluster-provision/gocli/opts/nfscsi/manifests/csi-nfs-node.yaml
Labels: size/L, kind/enhancement, approved, lgtm, dco-signoff: yes

#1331 Bump istio installation
  cluster-provision/gocli/opts/istio/istio.go
  cluster-provision/gocli/opts/istio/istio_test.go
  cluster-provision/gocli/opts/istio/manifests/istio-operator-with-cnao.cr.yaml
  cluster-provision/gocli/opts/istio/manifests/istio-operator.cr.yaml
  cluster-provision/gocli/opts/istio/testconfig.go
  cluster-provision/gocli/pkg/k8s/k8s.go
  cluster-provision/k8s/1.30/extra-pre-pull-images
  cluster-provision/k8s/1.30/provision.sh
  cluster-provision/k8s/1.31/extra-pre-pull-images
  cluster-provision/k8s/1.31/provision.sh
  cluster-provision/k8s/1.32/extra-pre-pull-images
  cluster-provision/k8s/1.32/provision.sh
  cluster-provision/k8s/1.33/extra-pre-pull-images
  cluster-provision/k8s/1.33/provision.sh
  cluster-provision/k8s/provision.sh
Labels: size/L, kind/enhancement, approved, lgtm, dco-signoff: yes

#1403 phases: Allow selecting phases other than the default again
  cluster-provision/k8s/base-image
  cluster-provision/k8s/provision.sh
Labels: size/XS, kind/enhancement, approved, lgtm, dco-signoff: yes

#1407 nfs-server: switch to well maintained image
  cluster-provision/gocli/opts/nfscsi/manifests/nfs-server.yaml
  cluster-provision/k8s/1.30/extra-pre-pull-images
  cluster-provision/k8s/1.31/extra-pre-pull-images
  cluster-provision/k8s/1.32/extra-pre-pull-images
  cluster-provision/k8s/1.33/extra-pre-pull-images
Labels: size/S, kind/enhancement, approved, lgtm, dco-signoff: yes
