Repository kubevirt/kubevirtci, pull requests merged in 2025-04, with the labels that each got.

#1415 Remove in-cluster nfs server in favor of external one
  cluster-provision/gocli/opts/nfscsi/manifests/0nfs-namespace.yaml
  cluster-provision/gocli/opts/nfscsi/manifests/0nfs-service.yaml
  cluster-provision/gocli/opts/nfscsi/manifests/csi-nfs-sc.yaml
  cluster-provision/gocli/opts/nfscsi/manifests/nfs-server.yaml
  cluster-provision/k8s/1.30/extra-pre-pull-images
  cluster-provision/k8s/1.31/extra-pre-pull-images
  cluster-provision/k8s/1.32/extra-pre-pull-images
  cluster-provision/k8s/1.33/extra-pre-pull-images
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/k8s-provider-common.sh
Labels: size/L, sig/storage, approved, lgtm, dco-signoff: yes, kind/cleanup

#1421 Fix cgroup v1 support
  cluster-up/cluster/K8S.md
  cluster-up/cluster/k8s-1.30/provider.sh
  cluster-up/cluster/k8s-1.31/provider.sh
  cluster-up/cluster/k8s-1.32/provider.sh
  cluster-up/cluster/k8s-1.33/provider.sh
  cluster-up/hack/common.sh
Labels: kind/bug, size/S, approved, lgtm, dco-signoff: yes

#1413 vm-image: Upgrade fedora-with-test-tooling to Fedora 39
  cluster-provision/images/vm-image-builder/example/image-url
  cluster-provision/images/vm-image-builder/example/image-url-arm64
  cluster-provision/images/vm-image-builder/example/os-variant
  cluster-provision/images/vm-image-builder/fedora-kubeadm/image-url
  cluster-provision/images/vm-image-builder/fedora-kubeadm/image-url-arm64
  cluster-provision/images/vm-image-builder/fedora-kubeadm/os-variant
  cluster-provision/images/vm-image-builder/fedora-realtime/image-url
  cluster-provision/images/vm-image-builder/fedora-realtime/image-url-arm64
  cluster-provision/images/vm-image-builder/fedora-realtime/os-variant
  cluster-provision/images/vm-image-builder/fedora-with-test-tooling/cloud-config
  cluster-provision/images/vm-image-builder/fedora-with-test-tooling/image-url
  cluster-provision/images/vm-image-builder/fedora-with-test-tooling/image-url-arm64
  cluster-provision/images/vm-image-builder/fedora-with-test-tooling/os-variant
Labels: size/S, kind/enhancement, approved, lgtm, dco-signoff: yes

#1427 cluster-up: update check for istio configs to check files that are actually copied after
  cluster-up/cluster/k8s-provider-common.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes, kind/flake
